### ISSUE TITLE
Nappy API is failing on requests near the end of the page limit

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#1032]
## Airflow log link

https://airflow.openverse.engineering/log?execution_date=2023-02-01T00%3A00%3A00%2B00%3A00&task_id=ingest_data.pull_image_data&dag_id=nappy_workflow&map_index=-1

> **Note**: _Airflow is currently only accessible to maintainers & those given
> access. If you would like access to Airflow, please reach out to a member of
> @WordPress/openverse-maintainers_.

## Description

Requests to the API near the end of the dataset appear to be returning a 500. On creation of this ticket, there were 2160 items. Examples (at different page sizes):

https://api.nappy.co/v1/openverse/images?page=21&per_page=100 (Supposed to be the last 100 results)

https://api.nappy.co/v1/openverse/images?page=216 (supposed to be the last 10 results with default page size of 10)

This appears to be the last successful page I can reach on the default page size: https://api.nappy.co/v1/openverse/images?page=206 (https://api.nappy.co/v1/openverse/images?page=207 fails).

I will also reach out to Nappy via email regarding this issue to bring it to their attention.

## Reproduction

(see above, this is deterministic)

## DAG status

Since most data successfully gets pulled and loaded, we can leave this one running. However, we'll add a alert silencing clause for this issue since this is a known error.

**Comment by rwidom** [comment]
I just clicked through on the links in the issue and didn’t get any 500 errors, but a) I didn’t test with python just firefox, and b) I didn’t really check for the data itself, just looked at the record counts which seemed to match what the issue said they should be. 

That said, https://api.nappy.co/v1/openverse/images?page=23 just repeats the same data from https://api.nappy.co/v1/openverse/images?page=22 without any kind of special message, so if that’s the plan going forward, we should probably turn off the dag until we can modify `NappyDataIngester.get_should_continue` right? [https://github.com/WordPress/openverse-catalog/blob/bbb8d97b23aea25df3edb716065a91[…]/openverse_catalog/dags/providers/provider_api_scripts/nappy.py](https://github.com/WordPress/openverse-catalog/blob/bbb8d97b23aea25df3edb716065a910f5ed1865c/openverse_catalog/dags/providers/provider_api_scripts/nappy.py#L51)

**Comment by stacimc** [comment]
We generally leave DAGs enabled if they are still consuming partial data. It looks like we're still getting a few thousand records before the error is hit. I see what you mean though, it _looks_ like that should cause the DAG to iterate over duplicates until it times out, but it doesn't seem like that's happening.

Weirdly, the DAG works just fine locally for me. No 500s, `get_should_continue` correctly identifies the stopping point. Can anyone else reproduce this locally?

**Comment by AetherUnbound** [comment]
Oh I didn't think to try this locally, I also mentioned on the make WP Slack that we use `page_size=100` - I am seeing that if you request pages after the total page count (23 at the time of writing) it just gives you back the results from the last page e.g. https://api.nappy.co/v1/openverse/images?page=25&per_page=100
That would seem to imply that it would run on until timeout as Staci mentions, but odd that we can't reproduce locally! I'll try this as well.

**Comment by AetherUnbound** [comment]
Oh I got it! The `next_page` parameter is missing from the final page, which we already check here: https://github.com/WordPress/openverse-catalog/blob/af205795b412da9f3d0d7f6d7e066b7d039b1763/openverse_catalog/dags/providers/provider_api_scripts/nappy.py#L52

So this should actually be fixed now!
