### ISSUE TITLE
Fix Wikimedia image titles

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#107]
## Current Situation

Currently, many images from Wikimedia have titles like `File:<name>.jpg`.
<img width="390" alt="Screen Shot 2021-06-18 at 6 56 13 PM" src="https://user-images.githubusercontent.com/15233243/122587889-10fa9a80-d067-11eb-965c-26ef02c44b0e.png">

## Suggested Improvement

We should use a different field to get title, or remove the 'File:' and '.ext' parts from the file name.

## Benefit

It will make search results look cleaner.

**Comment by dhruvkb** [comment]
I agree with dropping the `File:` prefix (it's also present in audio files) but I think having the extension on the file name is okay. The extension at least adds one bit of extra information which the `File:` prefix doesn't.

**Comment by obulat** [comment]
No other provider has a file extension in the file name, so I think it would be better to unify this.
