### ISSUE TITLE
Update references to `just airflow` in README

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#1076]
## Description

The README makes reference to the `just airflow` command which no longer exists. This was replaced by `just run`, e.g. `just run airflow ...`. Any references to the former need to be updated to the latter usage pattern.

https://github.com/WordPress/openverse-catalog/blob/main/README.md#setup

**Comment by Prathamdas3** [comment]
Can I work on this issue ?

**Comment by zackkrida** [comment]
Sure, @Prathamdas3. I've assigned you; thanks!

**Comment by Prathamdas3** [comment]
@zackkrida, 
which is used as command 'just run' or 'just run airflow'?
Does it needs argument to run ?

**Comment by AetherUnbound** [comment]
@Prathamdas3 this line:
https://github.com/WordPress/openverse-catalog/blob/8f8c15f184d1057bcb2bda6d11c0c5917c579e6b/README.md?plain=1#L187

Can be changed to `just run airflow config list`
