### ISSUE TITLE
Retire "update_phylopic_foreign_identifier" DAG

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-catalog#1077]
## Description

The DAG was was designed to run once and has already served its purpose. We can now decommission it to avoid having noise in the DAG list.

To solve this issue move the file to the `openverse_catalog/dags/retired/` folder.

## Alternatives

Another solution is just to delete the file.

## Additional context

Follow up to #1074.

**Comment by ArslanYM** [comment]
Can I fix this?

**Comment by ArslanYM** [comment]
![thiss](https://user-images.githubusercontent.com/104521101/229345129-8ab75376-ca6f-4b1b-be96-2a19ea6c0fbb.png)
Moving the above shown file to the retired directory should fix the issue right>
