### ISSUE TITLE
Update Europeana endpoint and accomodate v2 API changes

### ISSUE THREAD

**Issue by dravadhis** [WordPress/openverse-catalog#109]
## Current Situation

1. The current integration of the Europeana API uses the `https://www.europeana.eu/api/v2/search.json` endpoint. However Europeana has changed it's API endpoint to `https://api.europeana.eu/` to better manage traffic. This change has been noted in their API docs [here](https://pro.europeana.eu/page/search#get-started). Corresponding change should be made in the present API integration script. 
2. Some fields have been changed in v2 API. The backward compatibility of v1 API may be stopped anytime. Hence the API script needs to be modified according to the new fields. ( [list](https://pro.europeana.eu/page/search#v1) of modified fields)
3. Above changes also need to be made in the test files wherever required.

## Suggested Improvement

In the Europeana provider script, change value of `ENDPOINT` to `https://api.europeana.eu/`. Update the provider script and test suite with new fields according to v2 API. Ensure that the scripts run properly after making the changes.

## Benefit

Currently the old endpoint is still working. However this might change. Accommodating above changes will ensure that Europeana integration is updated.

**Comment by zackkrida** [comment]
@WordPress/openverse-maintainers as far as I can tell the Europeana API is still backwards-compatible with the fields we are using. Is this GitHub issue the only reason our provider DAG for them is still disabled? Do we also need an API key? It would be nice to be able to run this while we await a contributor updating the script.

**Comment by stacimc** [comment]
@zackkrida I just checked and it looks like we _are_ also missing an API key for Europeana. I'll make a ticket for that; once we have that I agree, we should let the script run as it does seem to be backwards compatible for now.

**Comment by AetherUnbound** [comment]
@sarayourfriend it looks like you actually closed this too in #821 😮 Is that correct?

https://github.com/WordPress/openverse-catalog/pull/821/files#diff-30cf1cf9d75f477a0be73d1f788cc9eff37480c1a884bb444f849dce71b75205R159

**Comment by sarayourfriend** [comment]
I copied the existing URL, didn't make any changes there: https://github.com/WordPress/openverse-catalog/pull/821/files#diff-30cf1cf9d75f477a0be73d1f788cc9eff37480c1a884bb444f849dce71b75205L33

**Comment by AetherUnbound** [comment]
D'oh, missed that! I didn't read this issue carefully enough either 🙂
