### ISSUE TITLE
[Bug] Rename the source suggestion issue template

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-catalog#177]
Replace "CC Search" with "Openverse" in the "New Source Suggestion for CC Search" issue template.

**Comment by MuhammadFaizanHaidar** [comment]
@zackkrida @dhruvkb I would love to contribute to this issue. Sorry for me silly question as I am new to OpenVerse contribution can you please guide me on this issue. Thanks

**Comment by zackkrida** [comment]
Hi @MuhammadFaizanHaidar here's a few suggestions for finding a file in a repository:

- GitHub has a "go to file" screen where you can search for the name of a file. You can access this with the 🔍 icon on the repository homepage:
  ![CleanShot 2021-09-22 at 07 55 11@2x](https://user-images.githubusercontent.com/6351754/134339208-cb7936e4-5459-4d38-9cda-0d4ecd40621e.png)
- If you make a local copy of the repository, you could search for the file in your code editor. Here's how one might do that in Visual Studio Code, for example: https://stackoverflow.com/a/30108348

Finally, here's the file you are looking for:

https://github.com/WordPress/openverse-catalog/blob/main/.github/ISSUE_TEMPLATE/new-source-suggestion.md

**Comment by MuhammadFaizanHaidar** [comment]
@zackkrida Thanks a lot for a quick response. That really helped.
