### ISSUE TITLE
[Bug] Non-image content is being stored in the image table (original #438)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#18]
This issue has been migrated from the [CC Search Catalog repository](https://github.com/creativecommons/cccatalog/issues/438)

```
Author: aldenstpage
Date: Fri Jun 19 2020
Labels: Hacktoberfest,help wanted,🙅 status: discontinued,🛠 goal: fix
```
## Bug Description
It seems like the Wikimedia source doesn't exclude non-image content. Here is a small subsample of some audio files I've encountered:
```
2a01b0fa-73b6-4911-889e-b02d41cf125d    https://upload.wikimedia.org/wikipedia/commons/6/62/Nl-mbo-studenten.ogg
9cd47e61-9389-46e1-b7a6-c3dd0e9efbdb    https://upload.wikimedia.org/wikipedia/commons/8/82/Nl-medaillekans.ogg
ec982a83-f036-4286-aedb-c2a45e540cb7    https://upload.wikimedia.org/wikipedia/commons/7/78/Nl-mea_culpa.ogg
136a5a87-a196-43d4-a506-ea3db5eea1d8    https://upload.wikimedia.org/wikipedia/commons/a/a8/Nl-meanderende.ogg
8ed0e5d4-0b6a-439e-9577-58496b2a10a1    https://upload.wikimedia.org/wikipedia/commons/2/2b/Nl-meao.ogg
a79cbff6-5026-47fd-9479-4cc00c24d307    https://upload.wikimedia.org/wikipedia/commons/e/e7/Nl-meccano%27s.ogg
a4c81ad0-0dee-4e62-8ed0-b50b553ab77c    https://upload.wikimedia.org/wikipedia/commons/b/b6/Nl-meccano.ogg
1e22bf99-fc4f-48a0-85a8-a6c705f4e3aa    https://upload.wikimedia.org/wikipedia/commons/8/8f/Nl-meccanodoos.ogg
7c8140b8-7929-4649-9f41-74d37f5f87b1    https://upload.wikimedia.org/wikipedia/commons/f/f0/Nl-meccanodozen.ogg
8530ab64-41ed-439e-b160-912352624502    https://upload.wikimedia.org/wikipedia/commons/5/56/Nl-mecenaat.ogg
```
This will cause some trouble with invalid content making its way into our thumbnail proxy, our image crawler, etc.

Of course, it won't be possible to completely validate the content type of a work without checking headers, but I think it would be sensible to have a file extension allowlist that will parse out the file extension when it is available and exclude clearly non-image works. If this isn't especially widespread maybe it can be solved by making some tweaks to the Wikimedia API task.

--------
### Original Comments: 

*mathemancer* commented on Tue Jun 30 2020:

>After taking a peek at the API responses, it seems like a large number of files returned by an 'allimages' query are non-image file types.  I'm currently querying in our DB to see how large of a problem this is on our end.

I suspect we'll have to modify our Wikimedia Commons Provider API Script to avoid saving some non-image files.  This will end up being a bit ad-hoc, though.
[source](https://github.com/creativecommons/cccatalog/issues/438#issuecomment-651861257)

*mathemancer* commented on Wed Jul 01 2020:

>Further info:

It seems like the naming of that endpoint is outdated somehow.  However, we can get a 'mediatype' field in the result.  One of them, `BITMAP`, seems to cover the following MIME types:
```
			'image/x-bmp',
			'image/x-ms-bmp',
			'image/bmp',
			'image/gif',
			'image/jpeg',
			'image/png',
			'image/tiff',
			'image/vnd.djvu',
			'image/x-xcf',
			'image/x-portable-pixmap',
			'image/gif',
			'image/png',
			'image/x-png',
			'image/ief',
			'image/jpeg',
			'image/pjpeg',
			'image/jp2',
			'image/xbm',
			'image/tiff',
			'image/x-icon',
			'image/x-ico',
			'image/vnd.microsoft.icon',
			'image/x-rgb',
			'image/x-portable-pixmap',
			'image/x-portable-graymap',
			'image/x-portable-greymap',
			'image/x-bmp',
			'image/x-ms-bmp',
			'image/bmp',
			'application/x-bmp',
			'application/bmp',
			'image/x-photoshop',
			'image/psd',
			'image/x-psd',
			'image/photoshop',
			'image/vnd.adobe.photoshop',
			'image/webp',
```
Unfortunately, the MIME type doesn't appear to be directly available.  However, restricting to just the `BITMAP` media type should avoid the audio files at least.
[source](https://github.com/creativecommons/cccatalog/issues/438#issuecomment-652230886)

*mathemancer* commented on Wed Jul 01 2020:

>So, the implementer should add `mediatype` to the `iiprop` query param list in the requests, and only save an 'image' if it has `mediatype: BITMAP`.
[source](https://github.com/creativecommons/cccatalog/issues/438#issuecomment-652231495)

*mathemancer* commented on Wed Jul 01 2020:

>Once this is done, we can clean up the DB.
[source](https://github.com/creativecommons/cccatalog/issues/438#issuecomment-652231590)

**Comment by obulat** [comment]
This issue has been closed in https://github.com/creativecommons/cccatalog/pull/453

**Comment by obulat** [comment]
Although the Wikimedia script was fixed, the database still has audio items that are saved as images. Here's one of them: https://wordpress.org/openverse/image/8107222e-fb67-42f2-a202-313922518a02 You can see that it shows the "Image not available" thumbnail.
We will need to clean up the database.

**Comment by krysal** [comment]
I found another audio registered as an image: http://localhost:8443/image/f2830b6e-a042-40fb-b2b4-62d1765be6ca

Why was this lowered to **medium** priority? Looks like a moderately severe bug to me.

**Comment by krysal** [comment]
Given the Wikimedia DAG is fixed, I investigated how many bad rows we need to remove from the image tables (Catalog and the API) by querying the **upstream DB** primarily. Since the problem is limited to the subset of the Wikimedia provider, the queries were not prohibitively slow, taking around half an hour, so I was able to run a couple and these were the results:

1. Most of the Wikimedia data was ingested in the 2020 year and had no `filetype` registered (the current [count for Wikimedia](https://api.openverse.engineering/v1/images/stats/) is 54269722 _images_).

```sql
SELECT EXTRACT(YEAR FROM created_on) AS created_on_year, COUNT(identifier)
FROM image 
WHERE source = 'wikimedia' AND filetype IS NULL
GROUP BY 1;

--  +-----------------+----------+
-- | created_on_year | count    |
-- |-----------------+----------|
-- | 2020.0          | 41817073 |
-- +-----------------+----------+
-- SELECT 1
-- Time: 1671.910s (27 minutes 51 seconds), executed in: 1671.891s (27 minutes 51 seconds)
```

2. I used a relatively simple regular expression to match every item with an URL ending with an audio file extension, so we will remove 1,444,762 rows or 2,66% of this provider's images. Not so bad in relation to the total content but still a lot of wrongly registered rows.

```sql
SELECT COUNT(*) FROM image
WHERE source = 'wikimedia' AND created_on < '2021-01-01 00:00:00'::timestamp
    AND url ~ '^.*.(flac|mp3|mid|oga|ogg|opus|wav|webm)$';

-- +---------+
-- | count   |
-- |---------|
-- | 1444762 |
-- +---------+
-- SELECT 1
-- Time: 1668.192s (27 minutes 48 seconds), executed in: 1668.175s (27 minutes 48 seconds)
```

The query to remove them will therefore use the same condition as the previous one:

```sql
DELETE FROM image WHERE source = 'wikimedia'
    AND created_on < '2021-01-01 00:00:00'::timestamp
    AND url ~ '^.*.(flac|mp3|mid|oga|ogg|opus|wav|webm)$';
```

@WordPress/openverse-catalog Does this plan seem correct to you?

**Comment by AetherUnbound** [comment]
That sounds great! It would be excellent if we could take the same approach to saving the data prior to deletion as I intend to take with the SMK data in #875.

**Comment by krysal** [comment]
Backup created and file stored at
```
s3://openverse-catalog/image/wikimedia_commons/wikimedia_deleted_2023_02_22.tsv
```

The result of the following commands:

```sql
CREATE TEMPORARY TABLE wikimedia_deleted_2023_02_22 AS (
    SELECT * FROM image
    WHERE source = 'wikimedia' AND created_on < '2021-01-01 00:00:00'::timestamp
        AND url ~ '^.*.(flac|mp3|mid|oga|ogg|opus|wav|webm)$'
);
-- SELECT 1444762
-- Time: 1791.045s (29 minutes 51 seconds), executed in: 1791.044s (29 minutes 51 seconds)

\copy wikimedia_deleted_2023_02_22 TO '/tmp/wikimedia_deleted_2023_02_22.tsv' DELIMITER E'\t' CSV HEADER;
-- Time: 5128.890s (1 hour 25 minutes 28 seconds), executed in: 5128.889s (1 hour 25 minutes 28 seconds)
```

I'll check tomorrow wether we need to create a snapshot of the Catalog database before running the `DELETE` command.

**Comment by krysal** [comment]
Backups checked

**Comment by krysal** [comment]
I applied the delete statement and already finished! The same number of items as queried before.

```sql
DELETE 1444762
Time: 2807.884s (46 minutes 47 seconds), executed in: 2807.884s (46 minutes 47 seconds)
```
