### ISSUE TITLE
[Bug] Duplicates in issue report

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#188]
## Description

There appear to be some duplicates in the new issue reporting page.

## Reproduction
1. Attempt to create a new issue
2. See duplicates of "Bug report" and "Feature request"

## Expectation
We should probably have just one per type.

## Screenshots
![image](https://user-images.githubusercontent.com/10214785/134606958-a77b4b7c-2fee-4570-8eed-cb0eabcfbf42.png)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
The list of issue templates are here: https://github.com/WordPress/openverse-catalog/tree/main/.github/ISSUE_TEMPLATE
