### ISSUE TITLE
Move API keys from .env to Airflow Variables

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#209]
## Current Situation

Provider API keys look to be set in the [.env file](./openverse_catalog/env.template).

## Suggested Improvement

These keys could be moved into Airflow Variables instead.

## Benefit

* As we expand our list of providers, the current strategy would require that we also bloat the environment with each of the new API keys.
* Airflow encrypts and hides Variables when they contain secrets.
* API keys can be edited without having to restart the service.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Excellent suggestion!

**Comment by AetherUnbound** [comment]
We've got a few options here, but my TL;DR for the time being is: keep things as is.

## Some potential approaches:
### Make Variables easy to access & edit

In the past, I've used Variables and Connections pretty heavily for API keys, secrets, etc. It's easy to use/update in the UI, provided that we have the "hide secrets" Airflow setting turned **off**. If that setting is on, it makes it much harder for engineers to introspect the keys and change things on the fly. That said, in my previous positions we also didn't have as many API keys to manage as we're likely to have here. This method also requires some manner of populating the Variables & Connections. Currently we're using env vars for this, which kind of defeats the purpose of _also_ putting them in Variables. A Variable means a call to the database, whereas an env var retrieval is bound to be much faster. Variables do allow us to change these values during runtime.

**Pros**:
- Easy for engineers to access & update API keys.
- Updates take affect immediately and apply to the next DAG run for a given service.
- Environment is not polluted with an ever-increasing number of API keys.

**Cons**:
- Values will need to be hand entered or have a programmatic creation in the `init` part of the entrypoint (work described in #227).
- In order to make this easiest for engineers, API keys would be exposed directly in the UI. This could be mitigated by creating multiple Airflow user roles with different permissions sets.
- Requires a DB call to retrieve the Variable. Particularly if this is added at the import-level along with everything else (#229), this will cause a significant slowdown in DAG processing time.

### Only use environment variables

This would mean all API keys end up in our environment somehow (either via `.env` or otherwise). With this approach, I think it might be best to standardize the names as `API_KEY_<provider>` so they all appear in the same location within the environment. This also opens us up for using an external secrets manager (like [AWS's option](https://aws.amazon.com/secrets-manager/)) to store those keys. The difficulty with the env vars is that we would have to restart the service/worker any time a key changes.

**Pros**:
- More secure.
- Keys can be managed externally more easily.
- Env lookups are very fast.

**Cons**:
- Updates to keys won't be propagated immediately and services must be refreshed to use the new keys. This becomes a moot point if we end up with something like Kubernetes, since workers are spun up on-demand in that case and will always have the most up-to-date info per DAG run (I assume).
- Engineers may have a harder time updating or introspecting these values in production.

---

Neither of these approaches really affect local development, as most engineers won't have or need all keys defined unless they're testing all DAGs. 

I think our best course of action is:
1. Keep things as-is for now.
1. Upon completion of #227, move keys to Variables and auto-create them at init time.
1. Should we move to some more complex deployment strategy like Kubernetes, move keys back to environment variables for more secure storage & sharing.

**Comment by AetherUnbound** [comment]
As I revisit this, I think one important facet of this will be 1) prefer adding variables into the UI for production and 2) prefer adding variables to the `.env` for dev. This doesn't much change how the code here will be modified, but I mention this because I believe we'll want to remove these values from the environment in production. Having them defined in the UI would mean (as described above) that we can update the API key without having to redeploy the entire service. This is bolstered by the fact that these variables live in the database, so even _when_ we do deploy the catalog they won't be lost. Since our environment in dev is intentionally meant to be thrown away, we'll want to keep them in the `.env` file there.
