### ISSUE TITLE
Move development services into compose override file

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#212]
## Current Situation

We have both `local_postgres` and `local_s3` set to spin up when the webserver is deployed. Neither of these are necessary in production, and end up getting stop after deployments.

## Suggested Improvement

Move those two services out into the `docker-compose.override.yml` file, so they get spun up for local development but not for production.

## Benefit

We only spin up the services that we need.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
This conflicts with #155 but I believe this is actually the correct approach: having production configs in `docker-compose.yml` and development configs in `docker-compose.override.yml`.

We should decide which one to keep. CC @zackkrida

**Comment by zackkrida** [comment]
@krysal I agree, and with `just` now it'll be easier to use the override files locally without confusion. I will update/close #155

**Comment by AetherUnbound** [comment]
Oops, I really should have checked the existing issues first before making all those :sweat_smile: Thanks for pointing that out @krysal
