### ISSUE TITLE
Add DAG tags

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#222]
## Suggested Improvement

Add DAG tags[^1] to all our DAGs so they can be more easily filtered by type/function.

[^1]: https://airflow.apache.org/docs/apache-airflow/stable/howto/add-dag-tags.html

## Benefit

Filtering becomes easier.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Amazing, this would be so nice. For provider scripts, cleanup/internal stuff, auth...we'll have to think of more categories but that shouldn't be too hard.

**Comment by AetherUnbound** [comment]
That's exactly what I was thinking!

**Comment by zackkrida** [comment]
some ideas (you probably have better ones 😆) with examples:

- provider (`brooklyn_museum_workflow`)
- provider-reingestion (`europeana_ingestion_workflow`)
- provider-metadata (`check_new_smithsonian_unit_codes_workflow`)
- ingestion-utilities (`tsv_to_postgres_loader`)
- utilities (`healthcheck_workflow`)

**Comment by AetherUnbound** [comment]
I'mm not as familiar with the variety of DAGs yet so those work great! We can always change them down the line if need be :slightly_smiling_face:
