### ISSUE TITLE
[Bug] Jamendo `audio_set->url` contains track ID in query params

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-catalog#234]
## Description

Consider a sample `url` inside the `audio_set` JSON field:

```
https://usercontent.jamendo.com?type=album&id=110159&width=200&trackid=938327
```

The `trackid` query param (which is not an attribute of the album) causes the album to appear several times in the data and interferes with the `DISTINCT` constraint imposed on the SQL.

The `trackid` param should be cleaned out of this field.

## Expectation

The data in the `audio_set` field should solely be related to the audio set. Extraneous data can affect the ability to uniquely filter out audio tracks from the data.

## Screenshots

<img width="2606" alt="Screenshot 2021-10-08 at 2 03 36 PM" src="https://user-images.githubusercontent.com/16580576/136537932-53c99581-644f-4bee-8eb4-df5aab9a0e44.png">

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
There is a mixup in the field naming. The actual URL that should be distinct is `foreign_landing_url` in the table on the screenshot. The `url` field actually has a URL of the set thumbnail (!), so there is probably no need in removing it. There is a field mixup in the `AudioStore`, and here is the data that is currently being written for audio_set:
```
{
  'title': 'Opera I',
  'foreign_landing_url': 'https://www.jamendo.com/album/119/opera-i',
  'url': 'https://usercontent.jamendo.com?type=album&id=119&width=200&trackid=730',
  'creator': 'Haeresis',
  'creator_url': 'https://www.jamendo.com/artist/92/haeresis',
  'foreign_identifier': '119'
}
```
Could you please confirm, @dhruvkb , if this is the naming that API expects (foreign_landing_url -> url, url -> thumbnail):
```
{
  'title': 'Opera I',
  'url': 'https://www.jamendo.com/album/119/opera-i',
  'thumbnail': 'https://usercontent.jamendo.com?type=album&id=119&width=200&trackid=730',
  'creator': 'Haeresis',
  'creator_url': 'https://www.jamendo.com/artist/92/haeresis',
  'foreign_identifier': '119'
}
```
