### ISSUE TITLE
[Feature] Update navbar color

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#236]
## Problem

We are using the default _(read: boring :wink:)_ navbar color.

## Description

Since we have brand colors now, we should use one of those! I find it's helpful to have different colors to distinguish easily between dev and prod. Possibly #ffe033 (brand yellow) for prod and #c52b9b (brand pink) for dev?

## Additional context

This can be changed using the `AIRFLOW__WEBSERVER__NAVBAR_COLOR` environment variable, we should add a default in our `env.template` file.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Examples:
![CleanShot 2021-10-09 at 12 41 29@2x](https://user-images.githubusercontent.com/6351754/136667031-c058e820-0fa5-44ca-b081-ae36d30fabe0.png)
![CleanShot 2021-10-09 at 12 40 11@2x](https://user-images.githubusercontent.com/6351754/136667034-0b83cc60-ba97-4ca2-adfa-07fd5329063f.png)
![CleanShot 2021-10-09 at 12 39 44@2x](https://user-images.githubusercontent.com/6351754/136667036-5dab3344-f01c-4e83-802a-80bbc517eb20.png)
![CleanShot 2021-10-09 at 12 39 00@2x](https://user-images.githubusercontent.com/6351754/136667037-8f34f615-3fe4-4f07-9276-229a4cb47f0f.png)

- pink: #C52B9B
- yellow: #FFE033
- dark: #30272E
- light: #F3F2F2

**Comment by dhruvkb** [comment]
From the screenshots, it appears that using pink and dark as backgrounds makes the text illegible.
