### ISSUE TITLE
[Bug] Flickr Provider API Script doesn't retrieve all unique items for a given day (original #326)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#26]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog/issues/326)

```
Author: mathemancer
Date: Fri Mar 13 2020
Labels: Hacktoberfest,help wanted,🙅 status: discontinued,🛠 goal: fix
```
## Bug Description

When the Flickr Provider API Script is run for a given day, the output is a copy of the rows for the same ~4,500 items over and over.  Instead, it should collect around 80,000-90,000 unique items per day.

## To Reproduce

Run `python flickr.py --date 2018-08-20`, notice that the output is 90,000 lines long, but there are only 4,376 unique photos (repeated over and over).

## Expected behavior

There should be *far* fewer repeated photos in the output, and *far* more unique results per day.

## Additional context

This appears to be due to some bug in the API.  Basically, it's actually *returning* the same ~4,500 articles over and over when called for an entire day's worth of data and paging through the result.

I tried splitting the day into hours, half hours, and 15 minute blocks, to see what the results would be (i.e., I looped through the same day's data by hours, half hours, etc.).  The results were confusing, to say the least.  All these results are from `--date 2018-08-20`:
```text
|  split  |  rows   | unique |
+---------+---------+--------+
| day     |  90,000 |  4,376 |
+---------+---------+--------+
| hour    | 106,457 | 82,008 |
+---------+---------+--------+
| 30 min  | 115,723 | 84,326 |
+---------+---------+--------+
| 15 min  | 140,966 | 82,484 |
+---------+---------+--------+
```
It seems like splitting things up by some time interval is a good idea, but it's not clear what the appropriate time interval might be.

I also tried separating out the licenses (currently we ask for *all* CC licensed items in the same query), and looping through 15-minute intervals.  This resulted in  

129,435 rows, with 78,210 unique results.

--------
### Original Comments: 

*mathemancer* commented on Fri Mar 13 2020:

>We need to understand why this is happening in the first place before actual development is appropriate, but I'd welcome ideas from the community, or more experimental results.
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-598729510)

*mathemancer* commented on Fri Mar 13 2020:

>Further info:  If you re-run the job with one of the splits above, you get the *exact same* result, so at least it's deterministic, if not that easy to figure out.
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-598740997)

*subhamX* commented on Tue Mar 17 2020:

>Can I work on this issue?
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-599911546)

*mathemancer* commented on Thu Mar 19 2020:

>@subhamX You can start looking more closely into the effects of different requests breakdowns on what comes back from the endpoint.  It will require some data analysis.  This ticket is nowhere close to ready for coding yet, though.
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-601099605)

*kss682* commented on Wed Mar 25 2020:

>@mathemancer I was able to reproduce the error by running ``` python flickr.py --date 2018-08-20 ``` and the output was 

```
Total lines in tsv file 135499
Total distinct images are 8870
```
and then I ran the script with a delay of 15 min once , output.
```
Total lines in tsv file 1513
Total distinct images are 1513
```
Is this what you meant by spliting , I am a bit confused 
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-603872282)

*mathemancer* commented on Tue Mar 31 2020:

>@kss682 What do you mean by 'delay of 15 min'?  You modified it to run for one 15 minute interval?

The point of the chart above is that you can split a day into 15 minute intervals, then concatenate all the results together.  So, the 15 minute split above would be the results from splitting the day into 96 15 minute intervals, getting the data for each interval in turn, and concatenating the results.
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-606529098)

*mathemancer* commented on Tue Mar 31 2020:

>Here's an updated / expanded chart of results with the old script:

```
| hr_sp | minutes | tsv_rows | unique | dc'ed | tsv_row2 | uniq_2 | discr |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.05 |       3 |  344,781 | 80,341 |       |  344,781 | 80,341 |       |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.1  |       6 |                           |                           |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.2  |      12 |  152,720 | 80,689 | t     |  152,720 | 80,689 |       |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.3  |      18 |                           |                           |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.4  |      24 |  123,759 | 83,332 | t     |  123,759 | 83,332 |       |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.5  |      30 |  115,723 | 84,326 |       |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.6  |      36 |  114,949 | 84,748 | t     |  114,949 | 84,723 | u     |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  0.8  |      48 |  111,137 | 85,001 | t     |  111,137 | 85,001 |       |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  1.0  |      60 |  105,802 | 81,522 | t     |  105,802 | 81,522 |       |
+-------+---------+----------+--------+-------+----------+--------+-------+
|  1.2  |      72 |  102,845 | 74,905 |       |  102,845 | 74,905 |       |
+-------+---------+----------+--------+-------+----------+--------+-------+
```

`dc'ed` is a boolean giving whether I re-ran the script with the given setup.  If so, I put the results of the second run in the following columns.
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-606529997)

*mathemancer* commented on Mon Apr 06 2020:

>Additional context:

We've noticed some odd behavior from the Flickr API. In order to catalog all of
the CC-licensed images from Flickr, we've taken a strategy of paging through
using the `flickr.photos.search` function of the API.  In order to keep the
number of results for a given search smaller than 4,000 (as per the
documentation), we're partitioning by restricting the min/max upload date. A
sequence of requests might look like:

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534723200&max_upload_date=1534725000&page=1&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534723200&max_upload_date=1534725000&page=2&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534723200&max_upload_date=1534725000&page=3&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534725000&max_upload_date=1534726800&page=1&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534725000&max_upload_date=1534726800&page=2&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534725000&max_upload_date=1534726800&page=3&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534725000&max_upload_date=1534726800&page=4&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534725000&max_upload_date=1534726800&page=5&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534725000&max_upload_date=1534726800&page=6&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

https://api.flickr.com/services/rest/?method=flickr.photos.search&min_upload_date=1534725000&max_upload_date=1534726800&page=7&media=photos&content_type=1&extras=description,license,date_upload,date_taken,owner_name,tags,o_dims,url_t,url_s,url_m,url_l,views&license=1,2,3,4,5,6,9,10&format=json&nojsoncallback=1&per_page=500&api_key=REDACTED

Or, condensed to show only the differences between requests:

&min_upload_date=1534723200&max_upload_date=1534725000&page=1
&min_upload_date=1534723200&max_upload_date=1534725000&page=2
&min_upload_date=1534723200&max_upload_date=1534725000&page=3

&min_upload_date=1534725000&max_upload_date=1534726800&page=1
&min_upload_date=1534725000&max_upload_date=1534726800&page=2
&min_upload_date=1534725000&max_upload_date=1534726800&page=3
&min_upload_date=1534725000&max_upload_date=1534726800&page=4
&min_upload_date=1534725000&max_upload_date=1534726800&page=5
&min_upload_date=1534725000&max_upload_date=1534726800&page=6
&min_upload_date=1534725000&max_upload_date=1534726800&page=7

This example sequence of requests should (according to our understanding) pull
the requested metadata for all photos uploaded on 2018-08-20 between 00:00 and
01:00 UTC, which we split into two half-hour segments to avoid querying for more
than 4,000 images at once. We have noticed some discrepancies, however. For
example, the 'total' key returned by the sequence of requests above is
inconsistent. The requests above give the sequence of 'totals':

1289, 1416, 1473                          -- first half hour
2635, 2314, 2061, 3232, 3232, 3232, 3232  -- second half hour

Note that in the second half hour, the discrepancies are wide enough to change
the number of expected pages returned for the time period (6, 5, 5, 7, 7, 7, 7).
Given this, our current strategy is to assume the max 'total' and 'pages' that
we see in a sequence of requests is correct.

Because we are getting inconsistent results with half-hour time intervals (as
demonstrated above), we've also tried smaller time intervals (e.g., 24 minutes).
What we found, however, was surprising: We got *fewer* unique results (for the
entire day 2018-08-20, using an analogous strategy) than we did with half-hour
intervals.  The resulting chart of experimental results is in a previous comment.

The column `unique` is the number of photos for which we retrieved metadata,
using the strategy described above, with the only difference being the size of
the time intervals.

Apparently, we get the most unique results using 48 minute time intervals.
Unfortunately, we found a further issue:

The results returned by, say, dividing the day into half-hour intervals rather
than 48 minute are *not* a subset of the larger result set! There are photos in
the results when dividing 30 minutes that are *not* in the results when dividing
by 48 minutes (and vice-versa, obviously).

This seems to indicate that we cannot guarantee that we'll be able to retrieve
the metadata for, say, all images uploaded on 2018-08-20 by using the strategy
of pulling the data for time sub-intervals of the day.

Central question: Is there any strategy by which we can guarantee that we'll
retrieve the metadata for all (CC-licensed, publicly available) photos uploaded
on a given day?
[source](https://github.com/creativecommons/cccatalog/issues/326#issuecomment-609738961)

**Comment by stacimc** [comment]
I'm getting promising results so far using the dynamic time splitting strategy discussed in #934 for the Finnish DAG 🤞
