### ISSUE TITLE
Move default categories from API to providers scripts

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-catalog#292]
## Problem

The `category` field should be pre-populated for images as it is done for audio rather than assigned during data refresh [as performed currently](https://github.com/WordPress/openverse-api/blob/e0949d2641f20506338dc6a40250c24f5a8fa517/ingestion_server/ingestion_server/categorize.py). So default categories need to be transferred here to be used in each corresponding provider API script.

## Additional context

New sample data for images, containing the `category` column would be needed in the API. Reference to WordPress/openverse-api#357.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
The `category` column is already a single string value (done in #243) so what remains is to populate it for images when it is possible: if the provider indicates the category in the API, or when we can ensure that all their images fall into a certain category by default.

Updating the issue accordingly.

**Comment by obulat** [comment]
Noting here that while working on this issue I discovered that our API categorization script does not work as we expect it.

Only images that were assigned a category by the catalog ingestion process (Stocksnap: photograph) have a non-null category in the API. To test it, try to search for 'digitized_artwork' or 'illustration' category in the API. It returns 0 results. The same happens on the front end, of course. If you select a category filter other than `photograph`, you will not get any results.
