### ISSUE TITLE
WP Photo Directory images missing author

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-catalog#322]
## Description

Viewing single results from the WP photo directory, the author name is not present. I am guessing this is a catalog level issue but have not looked into the DB yet.

## Reproduction

Visit https://wordpress.org/openverse/photos/f1d2a27a-054b-4f56-8507-c5bdc9c090d8 and observe the missing author information.

## Screenshots

![image](https://user-images.githubusercontent.com/6351754/148795513-282998ed-95fe-468c-914e-921a898f1cc0.png)

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
The API is returning invalid links for authors from the `wp-json/wp/v2/photos` endpoint and also is not returning all of them from `wp-json/wp/v2/users`, so I filled a new [Track ticket](https://meta.trac.wordpress.org/ticket/6313#ticket) for the latter. Let's wait and see how that is handled and whether it fixes the invalid links.

**Comment by zackkrida** [comment]
@krysal you've gotten some follow up on the trac ticket, including a PR to help with the problem:

https://github.com/WordPress/wporg-mu-plugins/pull/205
