### ISSUE TITLE
Incorrect download links for Freesound audio files

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-catalog#329]
## Description

Freesound download links in the `alt_files` list are currently:

https://freesound.org/apiv2/sounds/456258/download/

Which is the API endpoint for download that requires authentication, instead of:

https://freesound.org/people/NobodyYouKnowOf/sounds/456258/download/456258__nobodyyouknowof__rainbirdsthunder.wav

Which allows for downloading with a basic freesound user account in their Web UI. 

In the future, we could explore having our own `/audio/download` endpoint in the API that proxies freesound and allows for authenticated downloads, so I'm not sure what the best approach here is that future-proofs the catalog but also lets us give users the best experience now.

## Reproduction

1. Observe the urls in the `alt_files` array of an audio response: https://api.openverse.engineering/v1/audio/35a4adbe-bbb3-4911-ac5d-190491602b38/ are using the first format described above instead of the later one.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Hmm, unfortunately the API doesn't provide the latter URL :confused: It doesn't seem to be available in the list of fields returned by the API: https://freesound.org/docs/api/resources_apiv2.html#response-sound-instance

It _looks_ like we could construct the download URL ourselves by hand, if the format is regular. Would we want to go that route?

**Comment by zackkrida** [comment]
I can't speak for everyone but it might be best to keep the download urls we have, handle constructing these in the front-end, and plan for having that download endpoint long-term. I think that download endpoint would be the best approach for users long-term anyway

**Comment by AetherUnbound** [comment]
I'm alright with leaving as-is, though if we were going to construct the URLs ourselves I'd rather do it in the catalog than on the front-end. @WordPress/openverse-developers What do y'all think?

**Comment by sarayourfriend** [comment]
I think it's simpler than trying to construct the download URL ourselves.

Clicking the `.wav` link redirects to `https://freesound.org/home/login/?next=/people/NobodyYouKnowOf/sounds/456258/` which should look like a familiar format to anyone who's used Django auth before. The `next` parameter is much simpler than the full file download url. Can we just build this login page with a `next` param instead? It only requires the file ID and the username of the uploader which is at least one less piece of information (two if you count the file name format) than building the full URL out.

**Comment by zackkrida** [comment]
If we use `https://freesound.org/people/EminYILDIRIM/sounds/536078/download/536078__eminyildirim__eating-chips.wav`:

1. Users already logged-in to freesound will get the direct download
2. Users not-logged in will be redirected to the single result page (https://freesound.org/people/EminYILDIRIM/sounds/536078/) after logging in

I'm not sure we could build a `next` path that goes to the direct file.

**Comment by sarayourfriend** [comment]
Ah yes, I see. For logged in users https://freesound.org/home/login/?next=/people/NobodyYouKnowOf/sounds/456258/ takes you to https://freesound.org/home/ instead of even the freesound single result page. 

Never mind!

**Comment by krysal** [comment]
We will no longer offer downloads, so I'm closing this in favor of #667 which has already been fixed.
