### ISSUE TITLE
Create a tagged, versioned release

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-catalog#333]
It's been [quite some time](https://github.com/WordPress/openverse-catalog/releases) since the Catalog was given a formal release. It would be nice to make one soon, perhaps the next time we have some natural break in work or a time of transition between larger projects.

This version number tagging would be useful for our docker images too (perhaps relevant to #332).

**Comment by AetherUnbound** [comment]
Agreed! #332 should automatically enable tagged versions of the image similar to our other repositories :slightly_smiling_face:

**Comment by AetherUnbound** [comment]
Done! https://github.com/WordPress/openverse-catalog/releases/tag/v1.0.0
