### ISSUE TITLE
Rename the "ingestion server" to "data refresh"

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#368]
## Problem

We are using the legacy name "ingestion server" for a server that is performing our data refreshes (see https://github.com/WordPress/openverse/discussions/107).

## Description

I would like to propose that we rename the ingestion server and all associated assets (Docker images, private DNS names, references, etc.) to "data refresh" or "data refresh server". This will make it clearer what action the server is performing, particularly since we are still overloading the term "ingestion". Renaming it to `data_refresh` also helps us remove the redundant `_server` suffix everywhere.

## Alternatives

If anyone is **against** this change or would like to propose an alternate name, please do so by **2022-03-04**.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Sounds great. Should this be moved to the API repository?

**Comment by AetherUnbound** [comment]
Transfer went wonky but that's encapsulated in WordPress/openverse-api#567
