### ISSUE TITLE
Update API key for Smithsonian DAG

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#383]
## Description

We're missing an API key for the Smithsonian provider DAG. This causes the `pull_data` task to fail.

## Reproduction

Attempt to run the Smithsonian provider DAG in Airflow. Observe that the `pull_data` task fails and no data is ingested.

## Resolution

We need to:
* Obtain a new API key
* Configure the key in Airflow
* Re-run the DAG to make sure it's working

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Retrieved a new API key for `openverse@wordpress.org`, added it to our secrets manager and updated the list of API keys for Airflow.

I'm not able to log into Airflow though (the credentials in our secrets manager don't work for me) so pinging @stacimc and @AetherUnbound to feel free to update the Airflow variables with the one added in the secrets manager.

**Comment by stacimc** [comment]
Confirming the API key has been updated in Airflow 😄 Thanks!
