### ISSUE TITLE
Update API key for Brooklyn Museum

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#385]
## Description

We're missing an API key for the Brooklyn Museum provider DAG. This causes the `pull_data` task to fail.

## Reproduction

Attempt to run the Brooklyn Museum provider DAG in Airflow. Observe that the `pull_data` task fails and no data is ingested.

## Resolution

We need to:
* Obtain a new API key
* Configure the key in Airflow
* Re-run the DAG to make sure it's working

**Note**: Step 3 above is particularly important because this DAG _has not yet been run successfully in the lifetime of the project under Openverse_.

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
@dhruvkb were you able to get a response on the request?

**Comment by dhruvkb** [comment]
No, I expected they'd have a bot to mail out API keys but that does not seem to be the case. I'll follow up on the status of the request by emailing them.

**Comment by sarayourfriend** [comment]
@dhruvkb did you hear back from them?

**Comment by dhruvkb** [comment]
@AetherUnbound has recently mailed them from our HelpScout. We should hear back shortly I hope.

**Comment by AetherUnbound** [comment]
This is blocked pending a response from the provider.

**Comment by AetherUnbound** [comment]
It appears we can apply for a key here: https://www.brooklynmuseum.org/opencollection/api/register

I'm going to go ahead and do so, and will update our secret store with the results if I am accepted.

**Comment by AetherUnbound** [comment]
Update: we sent an email back in May, and I have since sent two separate requests for API keys. 🤞🏼

**Comment by dhruvkb** [comment]
Update: we now have the API key.

**Comment by krysal** [comment]
Saved!

**Comment by stacimc** [comment]
I believe we were waiting to close this issue until the API key is updated in production Airflow, and the Brooklyn DAG is re-run to test that it is working.

**Comment by AetherUnbound** [comment]
I tested this locally up to 6k records with success, just enabled in production. This can be closed!
