### ISSUE TITLE
Update API key for Walters DAG

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#386]
## Description

We're missing an API key for the Walters provider DAG. This causes the `pull_data` task to fail.

## Reproduction

Attempt to run the Walters provider DAG in Airflow. Observe that the `pull_data` task fails and no data is ingested.

## Resolution

We need to:
* Obtain a new API key
* Configure the key in Airflow
* Re-run the DAG to make sure it's working

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
I have reached out to a couple of contacts at the museum, but haven't heard back from them. I will try other contact, too

**Comment by sarayourfriend** [comment]
Any luck, @obulat?

**Comment by obulat** [comment]
Sorry I've missed this issue. Let me try sending the message to someone else.

**Comment by AetherUnbound** [comment]
This is blocked pending a response from the provider.

**Comment by obulat** [comment]
Should we close this issue considering that we are going to retire the DAG, @AetherUnbound?

See [the Make blog post](https://make.wordpress.org/openverse/2022/09/30/next-steps-for-walters-art-museum-data/), https://github.com/WordPress/openverse-catalog/issues/772, and https://github.com/WordPress/openverse-catalog/issues/773.

**Comment by AetherUnbound** [comment]
Oh, great call!
