### ISSUE TITLE
Update API key for RawPixel

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#387]
## Description

We're missing an API key for the RawPixel provider DAG. This causes the `pull_data` task to fail.

## Reproduction

Attempt to run the RawPixel provider DAG in Airflow. Observe that the `pull_data` task fails and no data is ingested.

## Resolution

We need to:
* Obtain a new API key
* Configure the key in Airflow
* Re-run the DAG to make sure it's working

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
@AetherUnbound Yes, partially. I got a response from them on March 20, saying they will discuss the situation with their team and get back to us as soon as possible. No more communication since then so I sent a follow-up email today as a reminder.

**Comment by AetherUnbound** [comment]
This is blocked pending a response from the provider.

**Comment by zackkrida** [comment]
I wonder if anyone from @rawpixel1 is active on GitHub?

**Comment by krysal** [comment]
Closing, as we successfully received the API key for Rawpixel. The `http://api.rawpixel.com` sub-domain has been shut down so the endpoint to use now is `https://www.rawpixel.com/api/v1`.
