### ISSUE TITLE
Finnish Museum `pull_data` freezes and times out

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#392]
## Description

The Finnish Museum provider DAG was recently turned on. The `pull_image_data` task begins running but then becomes stuck while getting the object list for the `0/Museovirasto` building. It eventually times out, incomplete.

The logs:

```
[2022-02-25, 00:46:13 UTC] {finnish_museums.py:37} INFO - Begin: Finnish museum provider script
[2022-02-25, 00:46:13 UTC] {finnish_museums.py:39} INFO - Obtaining Images of building 0/Suomen kansallismuseo/
[2022-02-25, 00:46:33 UTC] {finnish_museums.py:63} WARNING - No more retries 
[2022-02-25, 00:46:33 UTC] {finnish_museums.py:39} INFO - Obtaining Images of building 0/Museovirasto/
```

## Reproduction

Check out the `pull_image_data` logs for the Finnish Museum workflow in Airflow. You may also try re-running the DAG.

## Expectation
At minimum if the DAG has encountered an error, I would expect it to report the error and fail the task.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by stacimc** [comment]
Confirmed through logging that the API is getting hit successfully. It looks like we're not seeing anything written to disk because all the images returned are being [discarded due to an invalid license.](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/common/storage/media.py#L116) 🤔

**Comment by AetherUnbound** [comment]
Oh interesting, maybe that's the same issue with #391! I'm looking into that one now

**Comment by stacimc** [comment]
Okay, so I've discovered that the Finnish Museum API is returning results with an `image_rights` object, from which we're parsing license info. That object looks like:

```
{
'copyright': 'CC BY 4.0', 
'link': 'http://creativecommons.org/licenses/by/4.0/deed.fi',
 'description': ['Tiedostoa voi kä....]
}
```

And the issue is that the license url we're getting there is considered invalid because of the `/deed.fi` at the end. If I strip that part of the url it starts writing lines to disk 🤯 

I don't know enough about the licenses to understand what's going on with that link or whether that's something our license validation code should be able to understand

**Comment by AetherUnbound** [comment]
That's great! It looks like that links to the Finnish version of the 4.0 license _deed_, which appears to be the same as the 4.0 license page! I think it's safe to chop that bit off at the end and process the records normally :smile:

**Comment by zackkrida** [comment]
As I recall, here's the open source code for generating all of those static license information files! 
If we ever need to make updates to our license link parsing, @timidrobot is wonderful and they'd be a great person to inquire with.
