### ISSUE TITLE
Flag DAGs that are expected to fail to omit them from alerts

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#438]
## Problem

We have a couple provider DAGs running that we know have outstanding issues that will cause errors, but still allow for partial data to be processed -- for example, Wikimedia Commons is currently throwing a TypeError in its `pull_data` task (tracked in #436). We know the DAG will fail and have an issue set up to fix it, but in the meantime we'd like to keep the DAG turned on so we can continue getting at least some data.

The problem is that we still get Slack alerts. Folks who are unaware of the open issue may spend time investigating the error. It also just clutters up the alerts channel, particularly for daily DAGs.

## Description

Per a suggestion by @AetherUnbound 💯:

> it would be cool to use Variables to, on the fly, set DAGs that we know will fail. The slack alert could check for this as part of it's alerting logic. That'd allow us to set a known failing DAG in the UI but still let whatever records we catch get processed
 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by stacimc** [comment]
Something to think about: this does introduce the potential to accidentally forget to turn reporting back on for a DAG when its issues are fixed. It might be a good idea to introduce process, something like: if you're going to flag a DAG to turn off reporting, create a GH issue to turn it back on and link to the blocking work. So in the Wikimedia Commons example, I'd create a ticket to `Turn error reporting back on for Wikimedia Commons` and link it to #436.

**Comment by AetherUnbound** [comment]
Great point about the unintentional prolonged ignoration. I think another thing we could do is require that the list somehow be associated with a GitHub issue. For instance, the variable could be a dictionary that looks like this:
```
{
    "wikimedia_commons_workflow": "wordpress/openverse-catalog#436"
}
```

The existence within the dictionary would be enough to exclude it from reporting. We could then also have a weekly maintenance DAG that checks all of the associated GitHub issues to see if they are open or closed. If they're closed, issue an alert saying to turn it back on! That way we don't have to have follow up tickets for the work that gets done.

**Comment by stacimc** [comment]
> We could then also have a weekly maintenance DAG that checks all of the associated GitHub issues to see if they are open or closed. If they're closed, issue an alert saying to turn it back on!

This is such a cool idea, I'm sold! There's so much potential with Airflow that I haven't wrapped my brain around yet 😄

**Comment by AetherUnbound** [comment]
"Now you're thinking with Airflow" :grin:
