### ISSUE TITLE
Override default execution timeout for data refresh DAG sensors

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#447]
## Description

We ran into an issue recently where the data refresh DAG was poking the ingestion server status successfully, but was cut short prior to reaching the _sensor_ timeout. We realized that this was because we had reached the default _execution_ timeout:
https://github.com/WordPress/openverse-catalog/blob/962f1c5d9bb17bd6ea1ed5cc0674bab76d638f0b/openverse_catalog/dags/common/constants.py#L17

While this is a sensible timeout for typical tasks (e.g. the `HttpOperator` that triggers the data refresh), it's not ideal for the tasks that we know will be longer running. We still believe that having _some_ defined upper bound in general is a good policy - we'd rather add exceptions for longer tasks than never hear about a task that ran for days and days because we neglected to add an explicit timeout.

This timeout will only need to be added to the 2 sensor tasks in the data refresh DAGs.

We should also evaluate whether we should tune down the default sensor poke interval timeout, as it currently sits at one week.

## Reproduction

1. Start a data refresh DAG
2. Let it run for over an hour
3. Observe that the execution timeout gets reached

## Screenshots

**Airflow exception alert**
![image](https://user-images.githubusercontent.com/10214785/160663308-8448fb7d-dc78-4f12-be2f-c829274f957b.png)

**Execution timeout value under task instance details**
![image](https://user-images.githubusercontent.com/10214785/160663454-50f84420-8bf6-47de-8156-e8fc8ca169ef.png)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by stacimc** [comment]
You can't argue with the results of experimentation, which shows that our data refresh is timing out after 1 hour. _But_, confusingly, the Airflow documentation seems to suggest this shouldn't be happening: https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#timeouts

That suggests that `execution_timeout` gives a timeout for an _individual poke_, meaning in our case it should only fail if the Sensor takes more than an hour to poke the ingestion server and get a response. That should not be happening.

Meanwhile `timeout` should define the timeout for the entire task, from the start of the first execution until its eventual success. Meaning in our case that the Sensor would timeout if a week passes and the ingestion server still reports that the data refresh is active. (I agree that this could be tuned down some).

**Comment by stacimc** [comment]
Oh you know what -- I bet it's because `wait_for_completion` isn't explicitly in `reschedule` mode! I think that should fix our problem 🤦‍♀️

**Comment by AetherUnbound** [comment]
> Oh you know what -- I bet it's because `wait_for_completion` isn't explicitly in `reschedule` mode! I think that should fix our problem woman_facepalming

That's right, but the reason we have it in `poke` mode is so that it holds the pool slot until the data refresh finishes :no_mouth: It's possible that the `wait_for_data_refresh` sensor will handle that case appropriately...but I'm not certain

**Comment by stacimc** [comment]
Yep! When I was implementing the data refresh my thought process was "it doesn't _matter_ if `wait_for_data_refresh` frees the slot, because we expect it to block anyway", so I didn't bother putting it in `reschedule` mode -- but I didn't fully understand how the timeouts work so I didn't realize that would cause a timeout problem 🤦‍♀️ 

For others reading: it will continue to work because the `wait_for_data_refresh` sensor will correctly detect that the running data_refresh is "running" even if its `wait_for_data_refresh` is `up_for_reschedule`
