### ISSUE TITLE
Duplicated entries in `alt_files` of some Freesound audio

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-catalog#454]
## Description

I haven't confirmed if this is an ingestion issue, but it's probably just a matter of adding a validation step to the provider script, Freesound.

See for example:
- https://api.openverse.engineering/v1/audio/f28de5b2-642b-49ac-8bb3-67869c38b58a/ and
- https://api.openverse.engineering/v1/audio/2f9db0ec-6549-4e88-9950-bf6733f41fdb/

## Additional context

Related to WordPress/openverse-frontend#1180

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Nice find! I suspect there's some difference in the alt file metadata on fields we aren't tracking.

**Comment by AetherUnbound** [comment]
It looks like we're only _ever_ setting 1 alt file: https://github.com/WordPress/openverse-catalog/blob/e8400cd418df6651f7ff242b02f8f28431ac252c/openverse_catalog/dags/providers/provider_api_scripts/freesound.py#L249-L257

I suspect this is an issue with the upsert logic:
```
openledger> select count(*), updated_on, created_on from audio where jsonb_array_length(alt_files) > 3 and updated_on != created_on group by 2, 3;
+-------+-------------------------------+-------------------------------+
| count | updated_on                    | created_on                    |
|-------+-------------------------------+-------------------------------|
| 7497  | 2022-03-01 01:52:41.358292+00 | 2022-01-20 14:35:10.795854+00 |
| 715   | 2022-04-01 02:53:42.330805+00 | 2022-01-20 14:35:10.795854+00 |
+-------+-------------------------------+-------------------------------+
```
All of the records where this occurred were originally added in our first run, and have only ever been updated 😞

**Comment by AetherUnbound** [comment]
Indeed, here's the upsert query that's running: 
```sql
alt_files = COALESCE(
       jsonb_strip_nulls(old.alt_files)
         || jsonb_strip_nulls(EXCLUDED.alt_files),
       EXCLUDED.alt_files,
       old.alt_files
     ),
```

Here's an example where the two results are being `||`ed
```sql
openledger> SELECT COALESCE(jsonb_strip_nulls('[{"a": 1}]'::jsonb) || jsonb_strip_nulls('[{"a": 1}]'::jsonb), '[{"a": 1}]'::jsonb, null);
+----------------------+
| coalesce             |
|----------------------|
| [{"a": 1}, {"a": 1}] |
+----------------------+
SELECT 1
Time: 0.090s

**Comment by AetherUnbound** [comment]
From [the documentation](https://www.postgresql.org/docs/14/functions-json.html#FUNCTIONS-JSONB-OP-TABLE) _(emphasis mine)_:
> `jsonb || jsonb → jsonb`
> Concatenates two jsonb values. **Concatenating two arrays generates an array containing all the elements of each input.** Concatenating two objects generates an object containing the union of their keys, taking the second object's value when there are duplicate keys. All other cases are treated by converting a non-array input into a single-element array, and then proceeding as for two arrays. Does not operate recursively: only the top-level array or object structure is merged.
> `'["a", "b"]'::jsonb || '["a", "d"]'::jsonb → ["a", "b", "a", "d"]`

Looks like we'll need to find another way to manage that logic

**Comment by AetherUnbound** [comment]
WELL, it looks like we can make a function to accomplish this!
```sql
openledger> CREATE FUNCTION jsonb_array_distinct(jsonb) RETURNS jsonb AS $f$
   SELECT jsonb_agg(DISTINCT x) FROM jsonb_array_elements($1) t(x);
 $f$ LANGUAGE SQL IMMUTABLE;
CREATE FUNCTION
Time: 0.005s
openledger> SELECT jsonb_array_distinct('[{"a": 1}, {"a": 1}]'::jsonb);
+----------------------+
| jsonb_array_distinct |
|----------------------|
| [{"a": 1}]           |
+----------------------+
SELECT 1
Time: 0.019s
openledger> SELECT jsonb_array_distinct('[{"a": 1}]'::jsonb || '[{"a": 1}]'::jsonb);
+----------------------+
| jsonb_array_distinct |
|----------------------|
| [{"a": 1}]           |
+----------------------+
openledger> SELECT jsonb_array_distinct(COALESCE('[{"a": 1}]'::jsonb || '[{"a": 1}]'::jsonb, '[{"a": 1}]'::jsonb, NULL));
+----------------------+
| jsonb_array_distinct |
|----------------------|
| [{"a": 1}]           |
+----------------------+
SELECT 1
Time: 0.017s
```

YAAAAAAAAAY 🥳

**Comment by AetherUnbound** [comment]
I've asked a couple of different Postgres affinity groups and we'll see if they have any other suggestions. For next week, @WordPress/openverse-developers is a custom for this something we're comfortable with? We do already have precedent for other custom functions.

**Comment by zackkrida** [comment]
This looks like a good approach to me. 👍 The function seems wise since we definitely might need this elsewhere.

**Comment by krysal** [comment]
Great find @AetherUnbound! 💯 It seems quite reasonable to leave that job at the DB level since the upserting process already leverages many functions there 👍

**Comment by AetherUnbound** [comment]
Confirmed that this approach will also work to correct existing records (though we could always run it against them directly):
```sql
openledger> SELECT jsonb_array_distinct('[{"a": 1}, {"a": 1}, {"a": 1}]'::jsonb || '[{"a": 1}]'::jsonb);
+----------------------+
| jsonb_array_distinct |
|----------------------|
| [{"a": 1}]           |
+----------------------+
SELECT 1
Time: 0.028s
```

**Comment by AetherUnbound** [comment]
We...already have a function that does exactly that 😂 😭 🤦🏼‍♀️ 
https://github.com/WordPress/openverse-catalog/blob/88322d2da852324f1147417ff8da332721a9002a/openverse_catalog/dags/common/storage/columns.py#L57-L65

So I guess this is indeed a bug - we just need to change whatever typing information the `UPDATE` code is using for `alt_files`.
