### ISSUE TITLE
Do not show a load completion message if all steps failed

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#465]
## Description

The load completion reporting slack message will currently fire off in any case where the `pull_data_task` errored out. The intention behind this was to report partial loads, e.g. the provider script wrote 500 records to disk which _were_ loaded but errored out after that. We've recently encountered a case where the `pull_data_task` immediately fails before writing any records to disk. In this case, **both** `duration` and `<media type> count` were `None`. 

When the reporting step is reached, we should check to ensure that _at least one_ XCom value is not `None`. If all values are `None`, that means that an upstream failure occurred (so we should have already received an alert) and no rows were loaded (so we don't need the load completion message).

## Screenshots

![image](https://user-images.githubusercontent.com/10214785/161624042-eab0e2a6-18ff-4aa5-9ff2-ac8cdd79a6d3.png)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by rsubra13** [comment]
Hi - I would love to work on this ticket! thank you.

**Comment by AetherUnbound** [comment]
I've assigned you @rsubra13! 😄
