### ISSUE TITLE
Illustrations image type appears to not include any indexed images

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-catalog#491]
## Description

Filter by 'Illustrations' image type for several different search terms and see no results

Originally reported by @stacimc 

## Additional context

This could also potentially be handled by the API, perhaps each search term should actually also query ES for the list of possible valid values for certain filter categories given the term (i.e., if the term would return 0 results if filtered for illustrations, then do not show the illustrations filter).

It could also be interesting to be able to search just by type (definitely an API issue at that point), like being able to search with no term for all illustrations.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
I believe that this issue has been addressed in the catalog, as the following searches yield results:
* https://api.openverse.engineering/v1/images/?category=illustration
* https://search.openverse.engineering/search/image?q=illustration&category=illustration
