### ISSUE TITLE
SMK (statensmuseum) images taking too long to be validated

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#494]
## Description

When we recently tried to enable the `statensmuseum` provider, searches which included results from that provider ended up timing out on the Cloudflare -> API end. After some investigation, it appears that all the `url`s we have for `statensmuseum` images are taking a significant time to return (even on `HEAD` requests). This is causing validation to fail for all images returned in a result set, and I believe that the API isn't able to return a response quick enough for Cloudflare.

We are going to reach out to SMK to see if they can help us rectify this issue.

## Reproduction

1. Attempt a HEAD request: `time curl -I https://iip.smk.dk/iiif/jp2/KKSgb5781.tif.jp2/full/max/0/default.jpg`
2. Observe that it takes longer than our timeout of 2 seconds

## Expectation

These HEAD requests should ideally be very fast, and we should ideally be able to see Statens Museum results in the API.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Yes, the work necessary in #334 should fix this problem.
