### ISSUE TITLE
Durations less than 1 second are considered `None`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#497]
## Description

The code we are using to "humanize" the duration times doesn't react well to times that are smaller than 1 second:

https://github.com/WordPress/openverse-catalog/blob/v1.2.2/openverse_catalog/dags/common/loader/reporting.py#L33-L41

We should add a condition here to catch times that are <1s and return a string like "less than 1 second" or something similar.

## Screenshots

![image](https://user-images.githubusercontent.com/10214785/166586227-594909b7-9d54-416b-acc5-566a323bca0e.png)
![image](https://user-images.githubusercontent.com/10214785/166586247-460cf974-f30d-4f20-8c7c-a4ff068ca8f8.png)
![image](https://user-images.githubusercontent.com/10214785/166586262-380f8577-f93b-48d4-a5f0-6db1d0454879.png)

## Additional context

Came up during the testing for the v1.2.2 release: https://wordpress.slack.com/archives/C02012JB00N/p1651617702310709

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by rwidom** [comment]
🙋
