### ISSUE TITLE
Smithsonian subproviders check reports all unit codes as outdated

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#504]
## Description

The Smithsonian provider DAG [validates its list of subproviders](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py#L132) (or unit codes) before attempting to pull data. Sometimes, it reports that _all_ known unit codes are outdated and must be deleted. It seems like the Smithsonian API might be flaky. We should detect this and retry.

## Reproduction

1. Run the Smithsonian provider script locally a few times, until you see the error.

You can also look at the last few runs in production.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
> It seems like the Smithsonian API might be flaky

I don't have any known contacts there, but it might be nice to find someone we could reach out to there about this as well. 
I see the general openaccess@si.edu email address exists, not sure if there's a better point of contact.

**Comment by stacimc** [comment]
So far I've actually been unable to reproduce this locally 🤔
