### ISSUE TITLE
Ensure that all media have `license_url` in `meta_data` field

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#511]
## Problem

The API expects `license_name` and `license_version` to exist in the database. For the `license_url`, it checks if it exists in the `meta_data`, and if not, calculates the URL based on the license name and version.

In #66 we made sure that all the items add a valid `license_url` parameter to the `meta_data` field.   We can be confident that all data that was added after that PR contains `license_url`, but we need to check the older data.

Currently, there are 366,974 images that have a `NULL` value in `meta_data`, based on the following SQL query:
```
deploy@localhost:openledger> SELECT
 COUNT(*) as total,
 COUNT(*) FILTER (WHERE meta_data IS NULL) as meta_data,
 FROM image;
-[ RECORD 1 ]-------------------------
total                   | 563667181
meta_data               | 366974
SELECT 1
```
from the [public Slack chat message](https://wordpress.slack.com/archives/C02012JB00N/p1652848362174809?thread_ts=1652802243.895939&cid=C02012JB00N)

## Description

By checking the database for `license_url` and backfilling the values, if necessary, we can clean up the downstream API and frontend code that will expect the `license_url` to be present as a required field.

## Alternatives

We could continue computing the license URL as we do now, which would mean that we have duplicated code across the stack.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Some more details about this:

- `meta_data` object has two items: `raw_license_url` and the `license_url`. They have the same value if the provider gives the canonical license url: starting with `https`, with valid combination of license name, version, the jurisdiction (for ported licenses) and a trailing slash.
Prior to running any backfillling queries, we should do quick test for objects that there is no items with the following weird state: having the `raw_license_url` but no `license_url` in the `meta_data`. There probably are no such items, but it would be nice to check to be sure.

- It would be nice to see if we have any value for license version besides "N/A" (for publicdomain), "2.1" (for ported licenses only?), and "1.0", "2.0", "2.5", "3.0", "4.0".

My understanding is that if we have the license name and version, but no URL, in the database, then the license is not ported (i.e., does not have the jurisdiction at the end of the path, like `/jp`, `/au`, `/es`, because it's not recoverable from the two datapoints. _Or_ we have something like "2.1/jp" for the version value...

**Comment by AetherUnbound** [comment]
I'm trying one other query but in case I forget:
```sql
deploy@localhost:openledger> SELECT count(*) FROM image WHERE meta_data->>'license_url' IS NULL and meta_data->>'raw_license_url' IS NOT NULL;
+-------+
| count |
|-------|
| 0     |
+-------+
SELECT 1
Time: 881.233s (14 minutes 41 seconds), executed in: 881.226s (14 minutes 41 seconds)
```

Looks like we don't have any cases where `raw_license_url` is not null but `license_url` is :)
