### ISSUE TITLE
DAGs folder is not present in `PYTHONPATH`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#512]
## Description

Reported by @rwidom

When running `just ipython`, the DAGs folder is set as the current working directory, so imports from the `common` module and others work fine:

https://github.com/WordPress/openverse-catalog/blob/1fda166d6f8ac4cba14dce6c3c83207adc497cc2/justfile#L81

However, since the DAG folder isn't explicitly in the `PYTHONPATH`, `just shell` gives different results. The imports _will_ work after importing something from Airflow though, because Airflow modifies the `PYTHONPATH` to include the dags folder.

```bash
$ just shell
docker-compose --file=docker-compose.yml --file=docker-compose.override.yml up -d 
[+] Running 3/3
 ⠿ Container openverse-catalog-postgres-1   Running                                                                                                                                                            0.0s
 ⠿ Container openverse-catalog-s3-1         Running                                                                                                                                                            0.0s
 ⠿ Container openverse-catalog-webserver-1  Running                                                                                                                                                            0.0s
docker-compose --file=docker-compose.yml --file=docker-compose.override.yml exec webserver /bin/bash
airflow@649a98304b20:~$ python -c "from common import storage"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'common'
airflow@649a98304b20:~$ python -c "from airflow import settings; from common import storage"
airflow@649a98304b20:~$ PYTHONPATH=/usr/local/airflow/openverse_catalog/dags/ python -c "from common import storage"
```

We should add an explicit declaration of `PYTHONPATH` in the Dockerfile so that the DAGs folder is always available to python no matter how entering the container is performed.Probably somewhere around here: 

https://github.com/WordPress/openverse-catalog/blob/1fda166d6f8ac4cba14dce6c3c83207adc497cc2/docker/airflow/Dockerfile#L17-L18

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by tal66** [comment]
Hi, would this (in the Dockerfile) solve the issue? 
`ENV PYTHONPATH="${PYTHONPATH}:${AIRFLOW__CORE__DAGS_FOLDER}"`

**Comment by AetherUnbound** [comment]
Hi @tal66! Yes, but I think we could override the pythonpath entirely, e.g. `PYTHONPATH=${AIRFLOW__CORE__DAGS_FOLDER}`. We could also set a `DAGS_FOLDER` env var and set both the airflow setting and the python path to that value. Either approach is good 🙂 Would you like to tackle this one?

**Comment by tal66** [comment]
Yes. I'll do a PR tomorrow
