### ISSUE TITLE
Remove `thumbnail` field for images from the catalog

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#519]
## Current Situation

We get the thumbnail URL field from the providers but do not use it because we use the thumbnail proxy instead.

## Suggested Improvement

We should stop retrieving thumbnails from providers.
There are several things that need to be addressed here:
- [ ] Remove the `thumbnail` from provider scripts.
- [ ] We probably do not need to remove `thumbnail` from the common columns (TSV and DB) as audio (and maybe other media types) use them. I think it would be easier to set the image thumbnails to NULL.
- [ ] Clean up the database?

## Benefit

Slightly-improved performance and less data to store, data consistency.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Interesting! Would removing this have any implications for video or 3d models (not sure if models have thumbnails but I hope so!)

**Comment by obulat** [comment]
Well, I think we should leave the `thumbnail` field in the catalog as the field that is used for all types of media, but set it to null for images. We will need to investigate whether we want to use the thumbnails that are provided by the providers as we do with audio, or generate them just as we do with images.

**Comment by sarayourfriend** [comment]
> Well, I think we should leave the thumbnail field in the catalog as the field that is used for all types of media, but set it to null for images. We will need to investigate whether we want to use the thumbnails that are provided by the providers as we do with audio, or generate them just as we do with images.

Okay! That makes sense :+1:
