### ISSUE TITLE
Investigate the need for running `categorize` over the database

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#525]
## Problem

Currently, we do the categorization of the images in both the API ingestion server and the catalog.

## Description

We should investigate whether the `categorization` is needed for images in the catalog. If so, we should run `categorization` over the catalog database, and then leave this step only for the first ingestion. That would mean removing `categorize` from the ingestion server cleanup step.

**Comment by obulat** [comment]
Currently, some providers have a single category that should be applied to them:
https://github.com/WordPress/openverse-catalog/blob/3ee97b6cbe45337bec6289bd77b9a57512a82522/openverse_catalog/dags/common/loader/provider_details.py#L122-L143

Note that the Flickr value is inaccurate because Flickr has some other categories, too. And Stocksnap's category is already filled in in the database.

We can run `UPDATE` queries per provider to back-fill the `category` value. I tried doing so for the smallest set, `thorvaldsensmuseum`:

```
UPDATE image SET category = 'digitized_artwork' WHERE provider='thorvaldsensmuseum';
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
UPDATE 5356
Time: 4.780s (4 seconds), executed in: 4.780s (4 seconds)
```

Here is the plan of queries we would need to run to finish the category back-filling queries for all providers with single default categories. Numbers are taken from [Openverse sources page](https://wordpress.org/openverse/sources).
| provider | category | image count | note
| --- | --- | --- | --- |
"animaldiversity" | photograph | 15,554 | CommonCrawl source
"brooklynmuseum" | digitized_artwork | 63,340 | -
"capl" | photograph | 15,143 | CommonCrawl source
"clevelandmuseum" | digitized_artwork | 37,332  | -
"deviantart" | digitized_artwork | 238,982 | CommonCrawl source
"digitaltmuseum" | digitized_artwork | 289,769  | CommonCrawl source
"floraon" | photograph | 55,010 | CommonCrawl source 
"mccordmuseum" | digitized_artwork | 108,815 | CommonCrawl source
"met" | digitized_artwork | 255,420 | -
"museumsvictoria" | digitized_artwork | 160,720  | -
"phylopic" | illustration | 3,967 | - 
"rijksmuseum" | digitized_artwork | 29,999 | CommonCrawl source
"sciencemuseum" | photograph | 82,277  | - 
"svgsilh" | illustration | 358,942  | -
"thorvaldsenmuseum" | digitized_artwork | 5,356 | CommonCrawl source
"worms" | photograph | 19,783 | CommonCrawl source

**Comment by obulat** [comment]
Because the number of the media items that needed to be updated is rather low, I decided to run the updates. Now, all the providers listed in the table above have the correct category in the `upstream` table.

category | updated images count |  providers
| --- | --- | --- |
`digitized_artwork` | 1 242 237 | 'brooklynmuseum', 'clevelandmuseum', 'deviantart', 'digitaltmuseum', 'mccordmuseum', 'met', 'museumsvictoria', 'rijksmuseum'
`illustration` | 362 909 | 'svgsilh', 'phylopic'
`photograph` | 153 736 | 'animaldiversity', 'capl', 'floraon', 'sciencemuseum', 'worms'

With this, after we can run the data refresh, we can remove the [`categorize.py` module](https://github.com/WordPress/openverse-api/blob/81b7860e2662f4b135919da0728eea194f15c260/ingestion_server/ingestion_server/categorize.py) from the API that tries to compute the image category for Elasticsearch models during the ingestion.

**Comment by AetherUnbound** [comment]
This is great, thank you for running those updates @obulat!

**Comment by obulat** [comment]
I am going to close this issue as completed because the categories have been assigned.
