### ISSUE TITLE
Preserve trailing slash of URLs

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-catalog#531]
## Description

We're losing the trailing slash of URLs. This is confirmed to happen for the `foreign_landing_url` fields of the WordPress Photo directory script at least but should be affecting more sources, as is being removed from in the validation step.

We have to keep it since otherwise, it will cause redirection when the link is accessed.

## Reproduction

1. Copy the following test in `tests/dags/common/test_urls.py`
```python
def test_validate_url_string_keeps_trailing_slash():
    url_string = "https://wordpress.org/photos/photo/5262839486/"
    actual_validated_url = urls.validate_url_string(url_string)
    assert actual_validated_url == url_string
```
2. Run it with
```sh
just test -k url
```
3. See it fails.

You can also see the images from WP Photo Directory in wp.org/openverse redirecting (see the Network tab in the Developer tools of the browser) when clicking on the Source/Author link.

## Additional context

@dd32 was the first to notice. Ty!

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Oof, good find! My only concern here is that we might be unknowingly relying on this slash removal step for other providers. Do you think it would make sense to have an optional parameter specifying whether the slash should be removed? It could default to `True` but for the WP Photo Directory we could set it to `False`.

**Comment by krysal** [comment]
My idea was to keep the original URL received from the source, but I think there are some places where we may want the modified version. So yes, a param to remove or not the slash should be a good solution 👍

**Comment by thedevhaider** [comment]
Hello @krysal 👋, Can I work on this issue 🙋?

**Comment by krysal** [comment]
@thedevhaider Sure! Any help is much appreciated. I will assign it to you. You can also contact us at the **Making WordPress [slack channel](https://wordpress.slack.com/archives/C02012JB00N)** if you have questions.

**Comment by thedevhaider** [comment]
Thank you @krysal for assigning the issue. I can't signup for WordPress slack workspace. It says I need a `@chat.wordpress.org` email address for signing up. can you please help me with this?

**Comment by krysal** [comment]
Oops! My bad. Follow the instructions in this link to get your account: https://make.wordpress.org/chat/

**Comment by thedevhaider** [comment]
Thanks, @krysal, I am in 😄.
