### ISSUE TITLE
Investigate using Airflow's docker image as a base

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#532]
## Description

We're presently using `python:3.10-slim` as our base image. Airflow provides their own images that we could potentially use as an alternative base: https://airflow.apache.org/docs/docker-stack/index.html.

We should investigate whether this would be advantageous for us (easier to upgrade versions, not have to manage constraints, smaller image size, etc).

## Additional context

See #502 for more context

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by thedevhaider** [comment]
Hey @AetherUnbound, This issue looks interesting. Is it closed or active to take on?

**Comment by AetherUnbound** [comment]
It is still an active issue, and you're free to take it! Would you like me to assign it to you? 🙂

**Comment by AetherUnbound** [comment]
Looks like we can replace most of the logic in our custom entrypoint with either environment variables or the default entrypoint! https://airflow.apache.org/docs/docker-stack/entrypoint.html

One thing we should also do is split the stack into two separate containers, `webserver` and `scheduler`, which use the same image rather than running both in the same container.
