### ISSUE TITLE
Add a trailing slash on `foreign_landing_url` field of images of the WP Photo Directory to avoid 301 redirects

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-catalog#557]
## Description

We need to fix two things here:
1. Add the missing slash on existing images of the **WP Photo directory**
2. Keep the trailing slash on new ingested images of said provider. Previous related work on #531.

Feel free to take just one of the two tasks and create a specific issue if you want.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by thedevhaider** [comment]
Hello @krysal @AetherUnbound, Would like to work on point 2 of this issue. Can you please assign it to me?

**Comment by thedevhaider** [comment]
Hi @krysal 👋 , Just wanted to clarify something regarding point 2 of the issue. As per my understanding, We need to make sure `foreign_landing_url` field has a URL without a slash which is present in `openverse_catalog/dags/providers/provider_api_scripts/wordpress.py#164` so as to avoid 301 redirects. 
We are getting the value of `foreign_landing_url` from endpoint `https://wordpress.org/photos/wp-json/wp/v2/photos` under the `link` attribute from the API response. Please correct me if I am missing something 😄

**Comment by thedevhaider** [comment]
Also @krysal as per our conversation in this [PR](https://github.com/WordPress/openverse-catalog/pull/556), Is moving the `validate_url_string()` out of the column class (maybe to the MediaStore class) is part of the scope for this ticket?

**Comment by sarayourfriend** [comment]
That understanding is correct as far as I can tell @thedevhaider. It might be worthwhile to [open a Trac ticket to get the API to return the correctly formatted URL](https://meta.trac.wordpress.org/newticket?component=Photo%20Directory). In the meantime it doesn't hurt to add a line to format it on our end as well if it's missing the trailing slash.

**Comment by krysal** [comment]
@sarayourfriend The API returns the correct URL, the problem is we're removing the trailing slash in the validation step, there is no need to open a track ticket.

@thedevhaider yes, the goal of this issue is to keep the original URLs as we get them for the _WordPress Photo Directory_ script. An idea initially was to move that validation function up to the MediaStore class, so we can make use of your changes in #531 :) and will be able to fix this problem for future similar cases (we may need to check if this also is happening for other providers), but if you want to propose an alternative solution go ahead with it.

> We are getting the value of foreign_landing_url from endpoint https://wordpress.org/photos/wp-json/wp/v2/photos under the link attribute from the API response.

@thedevhaider That's correct, and potentially the same changes will apply to the `author_url` field (line 180) as well, obtained under the `_embedded.author.url` or `_embedded.author.link` (if the first one is not available) when the endpoint is requested with the `embed=true` param.
