### ISSUE TITLE
Investigate and fix inconsistencies in production audio data

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-catalog#558]
## Description

Checking on a number of bugs in the UI all of them seem to be caused by inconsistencies with the production data, so I'll put together the problems I've found here.

- [x] #559
- [x] #263
- [x] #561
- [x] #560
- [x] #562

**Comment by obulat** [comment]
Setting this `blocked` because we are actually waiting on successful Data refresh to confirm that it solves https://github.com/WordPress/openverse-catalog/issues/561

**Comment by AetherUnbound** [comment]
All of the underlying issues have been addressed, @krysal do you think we are clear to close this issue? 😄
