### ISSUE TITLE
Investigate audio files that have none as `filetype` in the database

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#559]
There are a lot of audio tracks with unknown` filetype`. We cannot rely on getting the extension by the URL because is not present there in many cases, we should modify audio provider scripts accordingly (Freesound, Jamendo and Wikimedia) and.

**Comment by obulat** [comment]
I checked both the upstream and the prod databases, and they do not have any items where `filetype` is `NULL`. Could you please give more details about this issue, @krysal ? How did you see the audio items without `filetype`?

**Comment by krysal** [comment]
That's great news! This was a question of mine, we can close this issue then and I will continue to investigate the extension/filetype issue on the API side. Thanks for checking on this!
