### ISSUE TITLE
Replace `sound` category with `sound_effect` in scripts and the database

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#562]
There are audio tracks categorized as "sound", which is not a valid API filtering category, they should be changed to `sound_effect`. E.g. https://api.openverse.engineering/v1/audio/3e3ea106-05e5-46bb-8fe4-8a2109cac00e/

**Comment by stacimc** [comment]
I suppose we could also add `sound` as a valid API filtering category (instead)? Taking a look back through Slack, it seems the `sound` category was originally introduced for short recordings of word pronunciations and was meant to be distinguished from `sound_effect` 🤔 

I think I would still prefer grouping both types into `sound_effect` -- that seems reasonable enough, and I imagine the current categorization might not be clear to a user even if we enabled it on the frontend. (What sorts of results would you expect to be categorized under "sound"?) Just curious what others think first before we update those records.

**Comment by stacimc** [comment]
Absolutely! I missed that `pronunciation` had been added at some point. Top of mind I've no idea what sort of data we continue to categorize as `sound`, and whether the pronunciation records were already recategorized -- I'll take a look!

**Comment by stacimc** [comment]
We have three audio providers to consider. Jamendo hardcodes category to `music` and should require no changes.

For Freesound I think we'll want to update `sound` records to category `null`. Unfortunately I don't see anything in the [API](https://freesound.org/docs/api/resources_apiv2.html#sound-resources) that would allow us to more accurately identify a category (music vs podcast vs etc).

For Wikimedia Commons, historically we only set the category to `sound` [when it was a pronunciation](https://github.com/WordPress/openverse-catalog/blob/6dd5cb34fb837caa969d2b597c8a8bdb12f089c7/openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py#L315). I think we can very simply update _all_ remaining records with that categorization to `pronunciation`.

SQL to run in production:

```
UPDATE audio SET category = NULL
WHERE provider = 'freesound' AND category = 'sound';

UPDATE audio SET category = 'pronunication'
WHERE provider = 'wikimedia_audio' AND category = 'sound';
```

The asterisk is that data refreshes are not currently running, so the data will not be updated in the API db until we can get them back up.

**Comment by krysal** [comment]
That approach and the queries look good to me 👍
