### ISSUE TITLE
Elasticsearch metrics reporting DAG

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#564]
## Description

It would be great if we could have a DAG that would regularly (possibly daily) generate some graphs of Elasticsearch metrics and report them to Slack. We've used our ES metrics as a proxy for determining when our API is being hit hard, and it would be helpful to have insight into those metrics in a form that doesn't require folks to log into AWS.

I think we should at least include **Network Data** and **CPU** in the metrics that are reported.

**Example**:
![image](https://user-images.githubusercontent.com/10214785/174922255-66bde930-9636-4bf4-9036-2816ff8879bd.png)

## Alternatives

We plan on having better metrics and alerting as part of our [monitoring project](https://github.com/WordPress/openverse/pull/193), but this will provide a solid stopgap until then.

## Additional context

We can use boto3's [`Cloudwatch::get_metric_widget_image`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html#CloudWatch.Client.get_metric_widget_image) function to generate the images. We will then have to either upload them to Slack or upload them somewhere that's publicly accessible so Slack can reference them. Our [Slack module](https://github.com/WordPress/openverse-catalog/blob/c4ffd95ddbb085eae3512622e82394ac39c7fb14/openverse_catalog/dags/common/slack.py) does not currently have the capacity to upload images, so if we went that route we'd need to add that functionality. Alternatively @sarayourfriend has suggested we use [pre-signed URLs in a private bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) - this will allow us to set expiration times to the links provided in Slack (up to 7 days).

I have some example code for how to potentially accomplish this here: https://github.com/WordPress/openverse-catalog/compare/main...feature/elasticsearch-metrics

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
> Our [Slack module](https://github.com/WordPress/openverse-catalog/blob/c4ffd95ddbb085eae3512622e82394ac39c7fb14/openverse_catalog/dags/common/slack.py) does not currently have the capacity to upload images, so if we went that route we'd need to add that functionality

How difficult would it be to add this? POSTing image blob data seems like it should be trivial with requests: https://requests.readthedocs.io/en/latest/user/quickstart/?highlight=multipart%20file#post-a-multipart-encoded-file

Between that and the S3 pre-signed URLs though I think choosing whichever is easiest should do the trick. Both seem like fine solutions.

**Comment by AetherUnbound** [comment]
Should be pretty easy! Here's [Slack's documentation on how to upload a file](https://api.slack.com/methods/files.upload). Only difficulty is figuring out what `token` is in this documentation and how it relates to our webhook URL 😄

**Comment by sarayourfriend** [comment]
It looks like with webhooks it's not possible to post files: https://stackoverflow.com/questions/35742775/is-it-possible-to-post-files-to-slack-using-the-incoming-webhook

Probably uploading to S3 is the shortest path forward, although creating a simple Openverse app token is probably trivial. It'll just require extending the full possibilities of the Slack HttpHook class...

**Comment by AetherUnbound** [comment]
Ah, that's unfortunate. Yea I think S3 is probably the best bet then 🙂

**Comment by AetherUnbound** [comment]
Closing this as we have (and will have) better reporting mechanisms.
