### ISSUE TITLE
Acquire Europeana API key

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#569]
## Description

We are missing an API key for the Europeana provider script.

This provider does need some updates due to API changes (#109) but as noted [here](https://github.com/WordPress/openverse-catalog/issues/109#issuecomment-1165759782) there is currently backwards compatibility (at least for now), meaning we can turn the script on and get data while we await updates, as soon as the API key is restored.

Link to apply for a key: https://pro.europeana.eu/page/get-api

## Reproduction

Run Europeana provider script locally and observe that it fails due to authentication errors (no API key provided). We don't have a key for production as far as I can find either.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
API key received.
