### ISSUE TITLE
[Infrastructure] Identify fields from which to obtain the foreign landing URL for certain Smithsonian museums (original #471)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#57]
This issue has been migrated from the [CC Search catalog repository](https://github.com/creativecommons/cccatalog/issues/471)

```
Author: ChariniNana
Date: Mon Jul 27 2020
Labels: ✨ goal: improvement,🙅 status: discontinued
```
## Current Situation
In the existing implementation of the Smithsonian provider API script, we initially try to obtain the foreign landing URL from `response.rows[i].content.descriptiveNonrepeating.record_link` and then from `response.rows[i].content.descriptiveNonrepeating.guid` if the former doesn't appear in the JSON response. However, for four of the Smithsonian museums (unit codes), neither of these fields exist. The four museum are as follows.
1. SIA (smithsonian_institution_archives)
2. NZP (smithsonian_zoo_and_conservation)
3. FBR (smithsonian_field_book_project)
4. NAA (smithsonian_anthropological_archives)

Since the foreign landing URL is a mandatory field, whatever images that do not contain it are dropped without being stored in the DB. Therefore, we entirely lose the prior mentioned four museums by Smithsonian.

## Suggested Improvement
Identify an alternative field from which the foreign landing URL can be obtained for these four museums.

## Benefit
The completeness of Smithsonian data collected would be considerably improved

## Additional context
Related to #397

**Comment by rwidom** [comment]
I looked at some sample files from the api, though it looks like they are really json-ish files stored on s3 (`s3://smithsonian-open-access/metadata/edan`) now. [Here](https://docs.google.com/spreadsheets/d/1Mi6nzJSMZ_MBuCbAwj5ucDpo2zUHsbCfIH5jxpiNyA8/edit#gid=1431590981) are the json paths that I found with any url data for these smithsonian subproviders. How should I handle references that are just text? (Also here's the branch with this info https://github.com/WordPress/openverse-catalog/tree/issue/57-smithsonian-landing-url )

**Comment by rwidom** [comment]
Hey @AetherUnbound , now that I looked more closely at the ingester class code, I think it's as simple as allowing for a single record to have more than one foreign landing URL in the same way that they have more than one image url. Unless you have other suggestions, I'm going to give that a shot and see how it goes.

**Comment by AetherUnbound** [comment]
Sorry, I was just taking a look at this! As always, your analyses are so helpful 🙌🏼 

> How should I handle references that are just text?

Are you referring to NAA here, which doesn't appear to have any viable results?

> I think it's as simple as allowing for a single record to have more than one foreign landing URL in the same way that they have more than one image url

What cases are we allowing more than one image URL? Do you mean like the SIA example that has multiple `online_media` indices? We've found that often times these other images from GLAM institutions are way less useful (see #1003 for us actually removing this from SMK). I think the first link we come across is the one that makes sense to use, as the others are likely to be alt images that may not have as much usefulness to them (for example, the `content.descriptiveNonRepeating.online_media.media.1.content.` image referenced in your sheet).

**Comment by rwidom** [comment]
Yes, I meant NAA and FBR (smithsonian_anthropological_archives and smithsonian_field_book_project), which don't seem to have any viable results.

And then, I just ran the dag (or a bunch of it) locally, and it looks like we already are catching and loading records for the other two subproviders / sources listed here -- smithsonian_institution_archives/SIA and smithsonian_zoo_and_conservation/NZP -- and which have the alternate images which we maybe don't want to get into.

So, I wonder if this might be a non-issue?

**Comment by AetherUnbound** [comment]
It's entirely possible this could be resolved! This is just an older issue that we've carried forward from Creative Commons, if you think we're covering all current cases as best we can, then feel free to close it 😄

**Comment by rwidom** [comment]
Closing.
