### ISSUE TITLE
Improvements to the PR Review Reminders DAG

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-catalog#571]
## Problem

The PR Review Reminders DAG is working as expected given it's current configuration, but after running it, I realized a few things that could improve about it.

## Description

0. Fix the line breaking in the comment so that the newlines present in the code aren't also used in the comment itself. This will make the comment look a little more natural.
1. Currently it will not resend the reminder if it detects that a reminder comment has already been sent. This works as a first pass, but ideally it would check if the comment was sent before the `updated_at` and the PR is past due again, then it should be safe to ping again. Consider potentially automatically deleting or at least hiding the previous ping comment so that it doesn't clog up any discussion happening in the PR comments.
2. Add the word "days" after the number of days for expected reviews given the configured urgency of the PR. In other words, turn "Ignoring weekend days, this PR was updated 29 day(s) ago. PRs labelled with medium urgency are expected to be reviewed within 4." into "Ignoring weekend days, this PR was updated 29 day(s) ago. PRs labelled with medium urgency are expected to be reviewed within 4 day(s).".
3. Do not ping when a PR already has two approvers, even if not all the assigned reviewers have reviewed.
4. We also want to add a Slack ping. This will require copying the GH to Slack ID mapping found in the infrastructure repository into an Airflow variable.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Some additional proposed changes, using an example. The little slashes in the usernames are meant to avoid pinging folks and aren't a suggested change.

Before:

> Based on the medium urgency of this PR, the following reviewers are being
> gently reminded to review this PR:
> 
> @/reviewername
> @/reviewername
> 
> This reminder is being automatically generated due to the urgency configuration.
> Ignoring weekend days, this PR was updated 4 day(s) ago. PRs
> labelled with medium urgency are expected to be reviewed within 4.
> 
> @/authorname, if this PR is not ready for a review, please draft it to prevent reviewers
> from getting further unnecessary pings.

After:

> Based on the **medium** priority of this PR, the following reviewers are gently reminded to review this PR:
> 
> @/reviewername
> @/reviewername
> 
> This reminder is automatically generated based on the priority configuration.
> Excluding weekend days, this PR was last updated 4 day(s) ago. 
> PRs labelled with medium urgency are expected to be reviewed within 4 weekdays.
> 
> @/authorname, if this PR is not ready for a review, please draft it to prevent reviewers from getting further unnecessary pings.

**Comment by sarayourfriend** [comment]
> We also want to add a Slack ping. This will require copying the GH to Slack ID mapping found in the infrastructure repository into an Airflow variable.

I think this will be more difficult. We'll need to set up an actual Slack app that can send DMs instead of the current implementation which relies exclusively on slack webhooks. Unless we want the pings to be public, but that feels weird to me.

cc @WordPress/openverse-maintainers

**Comment by zackkrida** [comment]
> Unless we want the pings to be public, but that feels weird to me.

This could make sense in the context of like a #openverse-pr-reviews channel, but it _is_ a bit odd.
