### ISSUE TITLE
Refactor Flickr to use ProviderDataIngester

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#585]
## Suggested Improvement

Refactor the Flickr provider script to use the new ProviderDataIngester base class

## Benefit

More details in #229

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Very excited for this one, in particular. There is one issue we aught to consider while working on it:

https://github.com/WordPress/openverse-catalog/issues/26
