### ISSUE TITLE
Refactor rawpixel to use ProviderDataIngester

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#592]
## Suggested Improvement

Refactor the **rawpixel** provider script to use the new ProviderDataIngester base class. The endpoint changed so to get the public domain content the request should look like this:

https://www.rawpixel.com/api/v1/search?tags=$publicdomain&page=1&pagesize=100&s=${signature}

To maintainers: see more info in the email received from them.

## Benefit

More details in #229

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
It appears we won't be able to receive or use direct image URLs without a signature attached. I've contacted Rawpixel to make sure we can use the direct image URLs safely and within the parameters of their API terms and conditions.
