### ISSUE TITLE
Refactor Thingiverse to use ProviderDataIngester

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#596]
## Suggested Improvement

Refactor the Thingiverse provider script to use the new ProviderDataIngester base class

## Benefit

More details in #229

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
I've posted about next steps for this refactor on the [Make WP Blog](https://make.wordpress.org/openverse/2022/10/10/next-steps-for-thingiverse-data/).

**Comment by AetherUnbound** [comment]
Closing this in favor of #820, see the Make WP post linked above for more context.
