### ISSUE TITLE
Refactor Walters Museum to use ProviderDataIngester

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#597]
## Suggested Improvement

Refactor the Walters museum provider script to use the new ProviderDataIngester base class

## Benefit

More details in #229

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
I've started work on this, but it seems like the API may no longer be operational 😞 

https://github.com/WaltersArtMuseum/walters-api/issues/75

**Comment by AetherUnbound** [comment]
Preliminary work on this is in https://github.com/WordPress/openverse-catalog/tree/feature/walters-refactor%23597

I'm stopping work on this for now and will write a Make WP post about it in a bit.

**Comment by AetherUnbound** [comment]
We will not be refactoring this DAG, but instead retiring it. See [the Make blog post](https://make.wordpress.org/openverse/2022/09/30/next-steps-for-walters-art-museum-data/), #772, and #773.
