### ISSUE TITLE
Use HEAD rather than GET for StockSnap::_get_filesize

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#631]
Is it also possible to change the `.get` to a HEAD request? https://github.com/WordPress/openverse-catalog/blob/cc7322b8916e604a9f7fd1a5f908677f9339ac8d/openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py#L158

That may be something for another issue.

_Originally posted by @sarayourfriend in https://github.com/WordPress/openverse-catalog/pull/628#pullrequestreview-1050925651_

**Comment by AetherUnbound** [comment]
We should probably add a `.head` method to the `DelayedRequester` so all the logic we have there can be reused!

**Comment by AetherUnbound** [comment]
Since we're only getting content from the response headers, my assumption was that a `HEAD` request would be better for this case because we neither need nor want the message body.

**Comment by krysal** [comment]
I remember getting different response headers when using the `HEAD` method so we have to be cautious that they're indeed interchangeable for the script's purposes.
