### ISSUE TITLE
Bump Airflow to >2.3.0

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#639]
## Description

While working on #636, we discovered that we might have run into https://github.com/apache/airflow/issues/23411. We are running Airflow v2.3.0 locally, so the issue should be addressed in [v2.3.1](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#id5) (via https://github.com/apache/airflow/pull/23674). 

As such we should upgrade our Airflow version to the latest (currently 2.3.3).

This will require a deployment since a new Docker image will be produced.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Swapping this out to critical, as it blocks our ability to test and re-implement data refreshes until fixed.
