### ISSUE TITLE
[Quality] Replace wildcard imports (from ... import *)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#65]
## Current Situation

In several files in `src/providers/commoncrawl`, there are wildcard imports. This is considered a bad practice in Python because it makes it difficult to see where a name comes from, and bloats the file's namespace. Read more: http://docs.quantifiedcode.com/python-anti-patterns/maintainability/from_module_import_all_used.html

## Suggested Improvement

We should replace the wildcard imports with specific imports that are used in the file. In some files, it is possible to see what needs to be imported by using the Git history (view Git blame -> View version before the change on GitHub; 'View history for selection' in Pycharm)

## Benefit

This will make the code more readable, and make it easier to find errors, if any.

**Comment by obulat** [comment]
The code in the `src/providers/commoncrawl/` works in the cloud, and will need to be tested when applying any changes. Until we set up testing environment for that workflow, this issue is blocked. For more background information, you can read comments to [ an old PR ](https://github.com/creativecommons/cccatalog/pull/499#pullrequestreview-489731677).

**Comment by AetherUnbound** [comment]
It looks like the last 2 places these are used are the `common/etl/scripts` (unused IIRC) and Thingiverse (which will be tackled in #596) so this can be closed after those are addressed!
