### ISSUE TITLE
Finnish museum `pull_data` exceeds timeout

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#665]
## Description

The Finnish Museum DAG has been consistently timing out at the `pull_data` step. Recently its `pull_data` task was updated to have a 5 day execution_timeout, but the most recent DagRun had to be manually failed after the task was still running after 15 days.

We should investigate why the task was able to exceed this limit.

## Reproduction

Observe the logs in Airflow for the run dated 2022-07-01.
You can also inspect the Task Instance Details and see that the `execution_timeout` is set to 5 days as expected.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
It is worth taking a look at #621 first to see if that would be one way to tackle the large amounts of data we receive from this provider.

**Comment by AetherUnbound** [comment]
Bumping this to high as the provider DAG is currently disabled.

**Comment by stacimc** [comment]
Investigating #621 now

**Comment by AetherUnbound** [comment]
@stacimc do you think this can be closed by #879 or do we need to run the DAG first to find out?

**Comment by stacimc** [comment]
@AetherUnbound Good question! I think it's probably fine to close, since we won't *really* know until we hit an ingestion day with a lot of data, and we can always re-open. In local testing, I was able to fully ingest data for one such day without hitting the timeout, so we should be good!
