### ISSUE TITLE
Add slack reporting steps for data refresh start & media popularity refresh

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#666]
## Description

The ingestion server already reports the status of the data refresh to Slack (see this module & search "slack" for examples"):

https://github.com/WordPress/openverse-api/blob/5baa15482da218e19fea7dc632f293571c39c682/ingestion_server/ingestion_server/ingest.py

The media popularity refresh steps were previously part of a separate DAG entirely, but were incorporated into the primary data refresh DAG as part of #496.

It would be great if we could have a Slack message at the beginning of the new data refresh DAG to show that the data refresh has started, and indicate which path it goes down (the regular weekly flow or the once-a-month popularity metrics refresh flow). This could potentially happen within the `month_check` task.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
If I'm understanding correctly, this was already implemented in #744, so @AetherUnbound do we need to do something else here or can we close this issue?

**Comment by AetherUnbound** [comment]
Oh, it is! This can be closed!
