### ISSUE TITLE
Use new format for Jamendo urls

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#667]
## Description

On the frontend we use the `url` to play audio previews. Currently, our urls from Jamendo have the format "https://prod-1.storage.jamendo.com/download/track/121465/mp32, where the track id and format are part of the path.

Jamendo is now recommending that we use a different endpoint using query params instead:"https://prod-1.storage.jamendo.com/?trackid=1279226&format=mp32"

Because the old format was causing errors on the frontend (https://github.com/WordPress/openverse-frontend/issues/1605), we've already updated all Jamendo records in place in the DB. **For this issue, we should update the Jamendo provider script to set the urls correctly during ingestion.** This will ensure that records ingested in the future don't cause the same issues.

When this is complete, we can turn the Jamendo workflow back on in production.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This issue also ensures that the format for Jamendo audio previews is using the `mp32` format, which has better browser support than something like `ogg`, for example.

**Comment by AetherUnbound** [comment]
@sarayourfriend mentioned that their v3.0 API doc example responses show that the newer URLs are returned

**Comment by AetherUnbound** [comment]
Sorry, slipped on the trackpad! The new URLs (i.e. `trackid=<track>` rather than `/track/<track>`) show up in their docs: https://developer.jamendo.com/v3.0/tracks
We'll just need to ensure that's the case for future runs.

**Comment by sarayourfriend** [comment]
Just for my curiosity: does this mean the ingested data will need to be re-ingested? If so, how does that work? I don't know if Jamendo is a "dated" DAG? Would that have an effect on the process one way or another?

**Comment by AetherUnbound** [comment]
Jamendo is _not_ a dated DAG, which means the entire dataset gets reingested on each run (default is `dated=False`):

https://github.com/WordPress/openverse-catalog/blob/1d407e813db57675bf989b0009c33a76c29914cd/openverse_catalog/dags/providers/provider_workflows.py#L113-L116

We corrected the existing data within the catalog database, but we shut the Jamendo DAG off for now until we can confirm that the ingester is receiving the new URL format. It's possible that this provider script won't require any updating at all, and future runs will simply receive the new URL format all on their own. We should verify that's the case, and if so we can close this ticket and re-enable the DAG!

**Comment by sarayourfriend** [comment]
Nice, thanks for the background. Very helpful :pray:

**Comment by zackkrida** [comment]
> Given that the data currently in the prod API is returning the new format for Jamendo URLs, is that enough confirmation?

No @sarayourfriend the production DB Jamendo urls were manually manipulated in the catalog DB prior to an audio data refresh, as a hotfix to UI issues on the frontend.

**Comment by sarayourfriend** [comment]
> No @sarayourfriend the production DB Jamendo urls were manually manipulated in the catalog DB prior to an audio data refresh, as a hotfix to UI issues on the frontend.

:scream: I see! This seems related to https://github.com/WordPress/openverse/issues/292

Yet another process available to us, I suppose.

**Comment by zackkrida** [comment]
The Jamendo DAG is paused and the dataset has been manually updated as a hotfix. Given these considerations I am lowering the priority of this issue to `high`.

**Comment by AetherUnbound** [comment]
Gah, unfortunately the current provider script is not loading the right URLs 😞 this is on a fresh run:

```
openledger> select url from audio limit 10;
+---------------------------------------------------------------+
| url                                                           |
|---------------------------------------------------------------|
| https://prod-1.storage.jamendo.com/download/track/100000/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100001/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100002/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100003/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100004/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100005/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100006/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100007/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100011/mp32 |
| https://prod-1.storage.jamendo.com/download/track/100014/mp32 |
+---------------------------------------------------------------+
```

This could either be because their API docs are incorrect or there's a field we're not using that we should.
