### ISSUE TITLE
Identify new Flickr sub-providers

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-catalog#676]
## Problem

For the flickr workflow we have a concept of sub-providers; collections within Flickr that are of particularly high quality. 

## Description

We should do a session of identifying more of these and adding them to the DAG.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by stacimc** [comment]
Here is a retired DAG for identifying sub-providers that we should look at as part of this: https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/retired/update_workflows/flickr_sub_provider_update_workflow.py
