### ISSUE TITLE
inaturalist data quality: issue warning with missing photo ids

### ISSUE THREAD

**Issue by rwidom** [WordPress/openverse-catalog#684]
## Current Situation

The initial PR for inaturalist left a couple of open questions related to data quality and structure: if a photo record has no photo id (foreign identifier), we ignore the record and do not load it, but we do not raise errors either.

## Suggested Improvement

Perhaps we should raise an error in airflow after a certain number of records without photo ids.

## Benefit

This has not come up in testing and there is reason to believe that it is very unlikely, but if it did happen an error could give an early heads up on serious data quality issues and save resources on a long-running dag.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
Changed this title a bit - I think ideally we wouldn't want this to halt execution/ingestion of images, but it would absolutely be good information to have for a given run if this exceeded some threshold!

**Comment by rwidom** [comment]
I just realized that there was a typo in the original text here, but I think that we can close this. The whole inaturalist system really depends on photo ids (e.g. that's how they identify the photo file on s3), so I think it's exceedingly unlikely that any record would make it into the tsv files without one.
