### ISSUE TITLE
Delayed requester's `DELAY` attribute should be public

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#687]
## Description

Currently, the delayed requester's delay-by value is private, i.e. `_DELAY`. There are instances in the provider data ingester where we may want to change this, but in order to do so we need to access the (currently private) attribute:

```python
    self.delayed_requester._DELAY = 3
```

## Additional context

See this comment for more context: https://github.com/WordPress/openverse-catalog/pull/674#discussion_r950519978

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Actually, this isn't needed at all because the provider data ingester allows specifying this at the class attribute level! 

https://github.com/WordPress/openverse-catalog/blob/ee474f2cbf6f797092ec7be3f56fef580f9c0a38/openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py#L57-L58

CC @rwidom

**Comment by rwidom** [comment]
@AetherUnbound , I think it's in the docs, but not the code, unless I'm just missing something? https://github.com/WordPress/openverse-catalog/blob/ee474f2cbf6f797092ec7be3f56fef580f9c0a38/openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py#L86

**Comment by AetherUnbound** [comment]
It can actually be set as a class attribute, here's an example:

https://github.com/WordPress/openverse-catalog/blob/1882d7776a16c6d7ebc9d0a28c502c25777c6a40/openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py#L18

That value then gets used at ingester initialization time when creating the delayed requester:

https://github.com/WordPress/openverse-catalog/blob/83c688d8354bd663a22835864f7aa18e3bdc9286/openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py#L107

**Comment by rwidom** [comment]
That makes much more sense. Thanks!
