### ISSUE TITLE
Add translations for top level taxonomies in inaturalist

### ISSUE THREAD

**Issue by rwidom** [WordPress/openverse-catalog#696]
## Problem
All of the descriptive text about photos from inaturalist is in Latin, which will make the search results less useful for users who are unfamiliar with the scientific nomenclature.

## Description
Taxonomies are trees though, so we could at least look up some higher levels terms (e.g. "birds" and terms in languages from the community rather than "aves") to include in our inaturalist metadata.

## Alternatives
We could try some kind of automated translation service, but it might not be that helpful. See https://wwf.panda.org/discover/knowledge_hub/teacher_resources/webfieldtrips/scientific_nomenclature/

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
I wonder if we could do some data augmentation and get a short summary about the species from Wikipedia and use it as a description. Wikipedia site is also great for looking up the names of species in various languages.

For instance, the title of the first result in the API search filtered by source (https://api.openverse.engineering/v1/images/?source=inaturalist) is _Buteo jamaicensis_. If you search for it in Wikipedia, you get redirected to the [page](https://en.wikipedia.org/wiki/Red-tailed_hawk) titled _Red-tailed hawk_. From there, you can get the name of the species in other languages simply by selecting the language in the sidebar or changing the URL to add the locale prefix. So, the Spanish version is at https://es.wikipedia.org/wiki/Buteo_jamaicensis. 

This is how I usually look up the species names in other languages, it is much better than a dictionary :)

**Comment by AetherUnbound** [comment]
That's true! I wonder if we could have a pre-ingestion step which sets up a lookup table in the `inaturalist` schema based on some public data. Looks like [folks have asked this before](https://biology.stackexchange.com/questions/52990/where-can-i-get-a-file-list-of-the-common-and-scientific-names-of-species) but unfortunately most of the links on that post are dead 😭

**Comment by obulat** [comment]
We could use the data from the Catalog of life. The [downloads](https://www.catalogueoflife.org/data/download) page has a `ColDP` zip archive. 
First, we would need to find the species code in the `NameArchive.tsv`, `46VWN` here:
| col:ID | ... | col:basionymID	| ... |
| --- | --- | --- | --- |
| 46VWN | ... | Neotrigonia margaritacea | ... |	

Then we can find the English "vernacular" name in the `VernacularName.tsv` file using that code. Simplified data example:

| col:taxonID | col:name | col:language | 
| --- | --- | --- |
| 46VWN | Australmuschel Australian | deu |
| 46VWN | brooch clam | eng |

**Comment by rwidom** [comment]
Ooh! Thanks! There's more on inaturalist taxonomic categories [here](https://www.inaturalist.org/pages/taxon_frameworks), but the taxa table isn't so big, so it wouldn't take too too long to cycle through looking things up the names in wikipedia.

**Comment by rwidom** [comment]
@obulat and @AetherUnbound do you think I can close this now that https://github.com/WordPress/openverse-catalog/pull/745 has been merged?

**Comment by obulat** [comment]
Yes, I think so. Awesome work, @rwidom!
