### ISSUE TITLE
Use `HEAD` request in Freesound ingester for file size request

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#754]
## Description

Dependent on #753 and #746

We should replace the `requests.head` call with the `DelayedRequester::head` call described in #753:

https://github.com/WordPress/openverse-catalog/blob/c332465db5dfdff41f9f89cd6792c01732a570be/openverse_catalog/dags/providers/provider_api_scripts/freesound.py#L172

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
I've bumped this to high because we're now seeing failures of the DAG occurring at this request. Specifically, if the URL 404s, this raises a `KeyError` for `content-length` ([example Airflow logs](https://airflow.openverse.engineering/log?execution_date=2022-11-01T00%3A00%3A00%2B00%3A00&task_id=ingest_data.pull_audio_data&dag_id=freesound_workflow&map_index=-1)). Using the machinery of the `DelayedRequester::head` method might help us address this.

**Comment by AetherUnbound** [comment]
Here's the failing sound in question: https://freesound.org/people/dl-jones/sounds/653078/

It looks like missing preview for a sound is indeed an issue with the Freesound data that we'll just need to account for. In these cases would we just want to skip the record entirely, since we can't preview it on our end? CC @WordPress/openverse-catalog

**Comment by zackkrida** [comment]
> In these cases would we just want to skip the record entirely, since we can't preview it on our end?

This is an interesting question, and I think it's okay to skip these records. The audio player is broken in FreeSound's frontend as well, which is a terrible user experience.

**Comment by AetherUnbound** [comment]
It's odd though, I just logged in and you _can_ download the audio file itself 🤔

**Comment by AetherUnbound** [comment]
I'm setting this priority to low since #920 is the issue that's actually affecting the DAG's ability to run successfully.
