### ISSUE TITLE
Do not log a period after an image URL

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#760]
## Description

Airflow across all browsers will render a URL at the end of a sentence as a URL with a period at the end. I encountered this while looking into #759. In the logs, the message `[2022-10-01, 00:17:59 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/MF8LSXR049.jpg.  Status code: 403` will create a URL with the value `https://cdn.stocksnap.io/img-thumbs/960w/AMEYDHBGJF.jpg.`, which will fail to resolve. However, the URL https://cdn.stocksnap.io/img-thumbs/960w/AMEYDHBGJF.jpg (note the missing period at the end) _does_ resolve. 

We should remove the period after the URL in this log line:

https://github.com/WordPress/openverse-catalog/blob/0072114ea479b378a94e1144340935023acbdf3d/openverse_catalog/dags/common/requester.py#L69-L72

Ideally, we'd also try to remove any other instances of this from the repo. A cursory search I did brought up a few more cases:

```bash
$ rg -e "url.*?}\."
archive/providers/commoncrawl/Provider.py
354:                    logging.warning('Content not found for url: {}, warc file: {}, offset: {}, length: {}.'.format(data[0].strip(), data[1].strip(), data[2].strip(), data[3].strip()))

openverse_catalog/dags/common/requester.py
70:                    f"Unable to request URL: {response.url}.  "
85:            logger.error(f"Error with the request for URL: {url}.")

openverse_catalog/dags/common/urls.py
57:            f"Invalid url {url_string}, attempted upgrade: {upgraded_url}."

openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
122:        image_url = f"{IMAGE_CDN}/{img_id}.jpg"

openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py
34:                f"Unable to request URL: {url}. Status code: " f"{response.status_code}"

openverse_catalog/dags/providers/provider_api_scripts/modules/etlMods.py
158:                f"Unable to request URL: {_url}. Status code:" f"{response.status_code}"

openverse_catalog/dags/common/licenses/licenses.py
225:        raise InvalidLicenseURLException(f"Failed to rewrite {derived_url}.")

openverse_catalog/dags/common/etl/scripts/ExtractCCLinks.py
59:        self.url = "https://{}.s3.amazonaws.com/crawl-data/{}/wat.paths.gz".format(

tests/factories/github/pull.json
47:      "compare_url": "https://api.github.com/repos/WordPress/openverse-frontend/compare/{base}...{head}",
192:      "compare_url": "https://api.github.com/repos/helpful-contributor/openverse-frontend/compare/{base}...{head}",
```

Notably:

https://github.com/WordPress/openverse-catalog/blob/0072114ea479b378a94e1144340935023acbdf3d/openverse_catalog/dags/common/requester.py#L85

https://github.com/WordPress/openverse-catalog/blob/0072114ea479b378a94e1144340935023acbdf3d/openverse_catalog/dags/common/urls.py#L57

https://github.com/WordPress/openverse-catalog/blob/0072114ea479b378a94e1144340935023acbdf3d/openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py#L34

https://github.com/WordPress/openverse-catalog/blob/88322d2da852324f1147417ff8da332721a9002a/openverse_catalog/dags/providers/provider_api_scripts/modules/etlMods.py#L158

https://github.com/WordPress/openverse-catalog/blob/0072114ea479b378a94e1144340935023acbdf3d/openverse_catalog/dags/common/licenses/licenses.py#L225

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by kamiwis** [comment]
Hi, I'd be interested in resolving this!

**Comment by AetherUnbound** [comment]
Hey @kamiwis! I'll assign it to you 😄 Let us know if you have any questions about this issue 🙂

**Comment by kamiwis** [comment]
Thank you! I submitted a PR that resolves the 6 instances you mentioned. I'm new to open-source contribution so please let me know if I can do anything differently! 🙂

**Comment by AetherUnbound** [comment]
The PR was perfect, thanks again for your contribution and welcome to open source! 😄
