### ISSUE TITLE
Update to new version of Phylopic API

### ISSUE THREAD

**Issue by rwidom** [WordPress/openverse-catalog#766]
## Current Situation
Phylopic has a new version of their API ([documented here](http://api-docs.phylopic.org/2.0/)), but we're still using the old one.

## Suggested Improvement
Let's start using the new one.

## Benefit
Eventually Phylopic will deprecate the old one.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
Oops, I didn't realize this was already made when I created #998! I'll close this in favor of the other since it has a bit more information attached to it, but thanks nonetheless Rebecca for making this issue 😄
