### ISSUE TITLE
Only report a deployment when DAG files are affected

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#785]
## Description

Presently we get deployment messages whenever the repo is updated (see the [`dag-sync.sh` file](https://github.com/WordPress/openverse-catalog/blob/28bfd1696fb362a5c7a8c6c46d603354920b6efa/dag-sync.sh) and [deployment documentation](https://github.com/WordPress/openverse-catalog/blob/28bfd1696fb362a5c7a8c6c46d603354920b6efa/DEPLOYMENT.md).

However, there are often cases where PRs that affect only dependencies, tests, or documentation are merged. These cases have no outstanding effect on the operational code which Airflow uses, and thus reporting their deployment is not as useful (and regarding dependencies, actually inaccurate since the dependency update won't be deployed until a release is cut and the whole service is redeployed).

We should modify the DAG sync script so it only issues a slack message if files within the `dags/` folder is modified, otherwise the slack message step should be skipped.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by ilitotor** [comment]
Hi,
I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
Thank you @ilitotor! I see you've already opened a PR, which we'll take a look at 😄 I've assigned the issue to you as well.
