### ISSUE TITLE
Add DAG documentation for refactored DAGs

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#803]
## Description

As we've been refactoring provider DAGs, we've been largely removing the files' docstrings. These were used by our dag docs tooling to generate the DAG documentation, so now our refactored DAGs are undocumented!

## Reproduction

Check out [DAGs.md](https://github.com/WordPress/openverse-catalog/blob/main/DAGs.md#provider) and observe that Cleveland, Museum Victoria, and several others have no documentation now.

## Screenshots

DAG docs generally look like this for providers:
```
"""
Content Provider:       Europeana

ETL Process:            Use the API to identify all CC licensed images.

Output:                 TSV file containing the images and the
                        respective meta-data.

Notes:                  https://www.europeana.eu/api/v2/search.json
"""
```

This would also be a nice opportunity to make the docstring a little more useful.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by stacimc** [comment]
cc @AetherUnbound for awareness 😱 Let me know if you think this should be prioritized higher, or added to the refactor milestone instead

**Comment by AetherUnbound** [comment]
Oh dear! FWIW I don't think we've been removing the documentation 😮 The file history for the DAGs file doesn't show any removals for the PRs you mention. I think we may have just not had that documentation in the first place! Those DAGs don't have docs on the original version of the file: https://github.com/WordPress/openverse-catalog/blob/0f58475427054c952eae859346d4aad3167b8131/DAGs.md#provider

Nonetheless, I think this is worth revisiting! I don't think we need to prioritize it higher though.

**Comment by stacimc** [comment]
Closing as a duplicate of #673 :)
