### ISSUE TITLE
Add `AudioCategory` enum

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#823]
## Description

We presently have an `ImageCategory` enum for the available image categories:

https://github.com/WordPress/openverse-catalog/blob/1506d6d9d391d7d12c8f5c515737623218036928/openverse_catalog/dags/common/loader/provider_details.py#L119-L122

It would be great if we could add a similar `AudioCategory` enum for our audio providers. This would include all of the available audio categories as defined by the API:

https://github.com/WordPress/openverse-api/blob/d9f83e53761dd502c93384f0aa6e2f7b711151e2/api/catalog/api/constants/field_values.py#L1-L8

## Additional context

It seems like every reference we have to one of the values is also `ImageCategories.<category>.value`, so I'm not sure we're getting much value out of this being an Python `Enum` derivative. We can probably just make this and the image categories an object that has each of those fields on it, e.g.:

```python
class ImageCategory:
    PHOTOGRAPH = "photograph"
    DIGITIZED_ARTWORK = "digitized_artwork"
    ILLUSTRATION = "illustration"
```

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by flamesjames** [comment]
Hello - I would love to take a stab at this as my first issue!

So you want the Enum derivative stripped from the ImageCategory class, and create the new class for AudioCategory? Anything else required?

Let me know if I misunderstood

**Comment by AetherUnbound** [comment]
Hi @flamesjames! Welcome 😄 Yes, you understood that correct. We'd like `ImageCategory` to become just a regular Python class for easier attribute access, and we'd like to _add_ an `AudioCategory` class which reflects the values in the API referenced above. Let me know if you have any other questions! I'll go ahead and assign this to you.

**Comment by flamesjames** [comment]
Sounds good! Thanks a lot. I will get this to you by EOD today.

**Comment by flamesjames** [comment]
Hello @AetherUnbound - QQ - I was trying to clone the forked repo to my local, but I was getting the following error:
```
error: invalid path 'tests/dags/common/test_resources/logs/test_dag/test_task/2021-08-10T00:00:00+0000/1.log'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

After some digging [online](https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl/61616948#61616948) and testing some things, I found that the root cause was due to the timestamp for those 2 log directories in the path `tests/dags/common/test_resources/logs/test_dag/test_task/`. After removing these 2 directories (given that it seemed to only have some test log files within it), I was able to clone the repo successfully.

Please let me know if you'd like me to add those back manually to my forked repo before creating the pull request, or if I'm free to leave out.

Thank you!

**Comment by flamesjames** [comment]
@AetherUnbound Oh gosh, no worries - I hope you are feeling better! 

Yes I am running on Windows 11, and it seemed after reading some resources online that it could either be the length or the formatting of the directory path that Windows doesn't like. I personally feel it was something with the formatting or potentially some of those special characters.

Is there any flexibility renaming those two directories to something without the special characters and re-deploying?

**Comment by AetherUnbound** [comment]
Thank you for looking into that, that's really good to know! Unfortunately those filenames are dictated by Airflow and we want to try and replicate the exact structure for testing 🤔 That said, I'll try to brainstorm some ways we can get around both the special character and or path length issues. I'll go ahead and create an issue for it 😄

**Comment by AetherUnbound** [comment]
Oh, it looks like your renaming of the files might have done the trick! Definitely seems like a `:` in the filename was what was tripping Windows up. I think most of the folks who develop Openverse on Windows use WSL, and we [note in our CONTRIBUTING.md](https://github.com/WordPress/openverse/blob/main/CONTRIBUTING.md#-note-for-windows-users) that we don't have active time to support native Windows contribution. That said though, it _seems_ like this fixes the issue without any other negative effects so I think it works for me!
