### ISSUE TITLE
PT-BR translation for README.md

### ISSUE THREAD

**Issue by gustavomfb** [WordPress/openverse-catalog#829]
I'm thinking in writing a translation for the readme file in pt-br. I know a lot of friends here in Brazil that uses this lib and actually can't speak/read english. What do you guys think about it and how should we make that? (I'm willing to translate)

**Comment by dhruvkb** [comment]
This seems like a great idea. One example I know of is https://github.com/casey/just which has a Chinese `README.中文.md` file and a message at the top of the English `README.md` linking to it.

One way to improve that could be to make a `README/` folder and put all translated copies of the `README.md` file in that folder.

**Comment by gustavomfb** [comment]
Nice! I'll aproach to the link in the top of readme. Could you assign me the task plz?

**Comment by AetherUnbound** [comment]
Fantastic, I've assigned you @gustavomfb!

**Comment by gustavomfb** [comment]
Done! Alredy linked the PR

**Comment by gustavomfb** [comment]
> Fantastic, I've assigned you @gustavomfb!

Let me know when u guys can make the review. It's a college project for Open Dev that i have to full translate a big git project!
@AetherUnbound
