### ISSUE TITLE
Investigate adding `pyupgrade` to linting checks

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#859]
## Description

We should investigate to see if [`pyupgrade`](https://github.com/asottile/pyupgrade) can be added to the project's pre-commit & linting checks, and whether or not it'd be beneficial to have it as part of our checks.

I have previously used this tool when upgrading projects from python 2 to python 3, however it seems there are even more checks we can locate if we specify a minimum python version with `--py3<version>-plus` (e.g. `--py38-plus`): https://github.com/asottile/pyupgrade#remove-parentheses-from-functoolslru_cache

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
This issue should go in `WordPress/openverse`. It can be beneficial in the API as well!

**Comment by AqeelAT** [comment]
Whoever takes this task will have their name on the lines edited by the initial linting, which means incorrect git blame information. If this is a concern, I can run the hook locally to asses the size of changes and then we can determine if a staffer should do it instead.

This is not a concern for #858 since the changes there should be minimal.

**Comment by dhruvkb** [comment]
@AqeelAT I don't think we'll mind which contributor's name is on the lint-fix commit. But it'll surely be helpful if you can open a PR that shows the impact of the change. 

As for the blame issue, we can add a `.git-blame-ignore-revs` to the repo; see the [Black docs](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame) for an example of how to use the `--ignore-revs-file` option.
