### ISSUE TITLE
Investigate adding `flynt` to linting checks

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#860]
## Description

We should investigate to see if [`flynt`](https://github.com/ikamensh/flynt) can be added to the project's pre-commit & linting checks, and whether or not it'd be beneficial to have it as part of our checks.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
I'm not sure if `flynt` is all that useful considering we always use f-strings wherever applicable in new code. Running it once to update any old usages should be sufficient? In any case, this issue should go in `WordPress/openverse`. It can be beneficial in the API as well!

**Comment by AetherUnbound** [comment]
I think having it as a regular check would still be useful, even if it's our present practice to use f-strings. That way the static checks are the ones to enforce that policy/idiom rather than us as maintainers 😄 I'll wait for your thoughts on #858 then take the same action here 🙂

**Comment by AqeelAT** [comment]
I would recommend using [pyupgrade](https://github.com/asottile/pyupgrade) over flynt since it does the same thing and more.

**Comment by AetherUnbound** [comment]
Thanks @AqeelAT! We have a ticket for that in #859. If we find it accomplishes the same thing as flynt we can close this issue and just use it instead 🙂

**Comment by AqeelAT** [comment]
Then I suggest we mark it as blocked by #859 so no one picks it up before that ticket is closed.

**Comment by sarayourfriend** [comment]
Given pyupgrade was accepted, this issue can be closed :tada:
