### ISSUE TITLE
Complete a full run of Freesound

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#931]
## Description

Making an issue for this so we can track the dependencies.

Before converting the Freesound DAG to a dated DAG, we should complete one successful "full" run of the DAG.

Blocked by:

- [x] #920
- [x] #659
- [x] #932

In particular, #932 is important to increase the delay between requests (in order to respect the stated rate limit) and to increase the `pull_data` timeout (so a full run can complete).

Once the blockers are merged, we should manually trigger a DagRun with `skip_ingestion_errors` enabled. Since the DagRun will take a long time to complete, we should check in every day or so to see if batches are getting skipped.

This issue should be considered closed when a full DagRun succeeds.

**Comment by stacimc** [comment]
#973 is open to solve #920 and just needs one more approval.
#943 is open to solve #932 and is fully approved/can be merged.

**Comment by AetherUnbound** [comment]
I think all the related PRs have been addressed! 😮 @stacimc shall we run this after the data refresh next week?

**Comment by stacimc** [comment]
> shall we run this after the data refresh next week?

@AetherUnbound given the status of the data refresh, do you think we should still wait on enabling Freesound?

**Comment by AetherUnbound** [comment]
Unfortunately, yea I think we should 😞

**Comment by stacimc** [comment]
I enabled Freesound on March 8th, hoping for a full run. After a day and a half it failed due to a `RetriesExceeded` error which appeared to be transient when tested locally.

I kicked off a second manual run, starting from the query parameters which caused the error. This run was proceeding well but timed out after 10 days.

**Comment by stacimc** [comment]
I opened a [PR](https://github.com/WordPress/openverse-catalog/pull/1058) to log the final query params hit when a task times out, so that we can more easily resume DAGs like this from the point they timed out.

In the meantime, I'll try to get a rough estimate of how far the DAG got so we can hopefully avoid re-triggering it from the beginning :/ We may also want to extend the timeouts even further, and perhaps temporarily set the `schedule` to `None` to avoid scheduled runs in the midst of this.

**Comment by AetherUnbound** [comment]
At the very least, given how long this takes, I think changing the schedule interval to `@quarterly` makes the most sense! If not `None` as you recommend (I just don't want to forget about it 😅)

**Comment by stacimc** [comment]
I think `@quarterly` is the long-term move for sure! I believe that would happen to queue up an April 1st run though, which is why I was thinking to do `None` for now. But maybe that's not so bad, we'll just have one queue up after the manual run somewhat unnecessarily.

The last run processed `152,500` records, and was manually started on page `145`. With `150` records per batch, that means it got through a little over `1,016` pages. So it should have left off somewhere around page `1,161`. To be safe, we could start it at page `1,150`.

I'll post a quick PR to make those schedule/timeout adjustments and once that's merged we can kick this back off.

**Comment by stacimc** [comment]
The schedule updates have been made and another run has been kicked off.

**Comment by stacimc** [comment]
I'm going to close this issue as all of its blockers are resolved and the DAG is enabled in production 🤞 We will be alerted to any new problems or timeouts via Slack and should open new issues as these arise.
